INSERT INTO multiplechoice_question (jenis_soal,sulit,nomor,question,parent_nomor,multiplechoice_img_code,jawaban) VALUES 
('accounting',1.66,1,'Sesuai dengan Pernyataan Standar Akuntansi Keuangan yang ditetapkan oleh Ikatan Akuntan Indonesia, komponen laporan keuangan yang lengkap terdiri dari sebagai berikut:',NULL,NULL,'C')
,('accounting',0.59,2,'Akun-akun berikut ini biasanya terdapat dalam laporan laba rugi dan penghasilan komprehensif lain sebuah perusahaan yang bergerak dalam bidang perdagangan, kecuali:',NULL,NULL,'A')
,('accounting',0.41,3,'Pihak-pihak berikut ini merupakan pihak-pihak yang berkepentingan terhadap laporan keuangan suatu perusahaan, kecuali:',NULL,NULL,'B')
,('accounting',-2.22,4,'Perusahaan membeli bahan baku seharga Rp 100, PPN 10%, jangka waktu kredit 2 bulan. Jurnal yang benar adalah (periodical method):',NULL,NULL,'C')
,('accounting',2.33,5,'Pada akhir suatu tahun buku, terdapat biaya-biaya bulan Desember yang belum dilunasi seperti: listrik, telepon dan biaya lain-lain berjumlah Rp 250. Jurnal yang harus dibuat adalah:',NULL,NULL,'C')
,('accounting',-2.35,6,'Sambungan soal No. {4} tersebut di atas. Sebelum jangka waktu 2 bulan, perusahaan melakukan pelunasan dan karena pelunasan dilakukan lebih awal maka perusahaan mendapatkan discount sebesar 2%. Jurnal yang harus dibuat adalah:',4,NULL,'D')
,('accounting',1.47,7,'Debt to equity ratio dihitung dengan cara:',NULL,NULL,'A')
,('accounting',-1.54,8,'Account receivables turnover dihitung dengan cara:',NULL,NULL,'D')
,('accounting',0.96,9,'Pajak penghasilan yang dikenakan terhadap pendapatan bunga deposito bank merupakan pajak penghasilan:',NULL,NULL,'B')
,('accounting',-2.15,10,'Pajak penghasilan yang disetor oleh suatu perusahaan setiap bulannya yang merupakan angsuran pajak dalam tahun berjalan merupakan pajak penghasilan:',NULL,NULL,'B')
;
INSERT INTO multiplechoice_question (jenis_soal,sulit,nomor,question,parent_nomor,multiplechoice_img_code,jawaban) VALUES 
('accounting',0.41,11,'Tarif pajak penghasilan untuk wajib pajak badan yang secara umum berlaku saat ini adalah:',NULL,NULL,'D')
,('accounting',-3.00,12,'Metode penilaian persediaan yang diperkenankan sesuai dengan undang-undang dan peraturan perpajakan yang berlaku saat ini adalah:',NULL,NULL,'D')
,('accounting',1.23,13,'Akun-akun berikut ini biasanya terdapat dalam laporan posisi keuangan sebuah perusahaan perorangan yang bergerak dalam bidang manufaktur, kecuali:',NULL,NULL,'A')
,('accounting',-1.10,14,'Akun-akun berikut ini biasanya merupakan komponen dari beban pokok penjualan dari sebuah perusahaan yang bergerak dalam bidang manufaktur, kecuali:',NULL,NULL,'D')
,('accounting',-0.29,15,'Perusahaan menjual produknya seharga Rp 100, PPN 10%, jangka waktu kredit 2 bulan. Jurnal yang benar adalah:',NULL,NULL,'C')
,('accounting',1.77,16,'Dalam suatu tahun buku, penyusutan mesin-mesin fabrik berjumlah Rp 150. Jurnal yang benar adalah:',NULL,NULL,'D')
,('accounting',1.77,17,'Sambungan soal No. {15} tersebut di atas. Sebelum jangka waktu 2 bulan, pelanggan melakukan pelunasan dan karena pelunasan dilakukan lebih awal maka perusahaan memberikan discount sebesar 2%. Jurnal yang harus dibuat adalah:',15,NULL,'C')
,('accounting',-2.77,18,'Current ratio dihitung dengan cara:',NULL,NULL,'A')
,('accounting',0.01,19,'Gross profit margin dihitung dengan cara:',NULL,NULL,'B')
,('accounting',2.53,20,'Pajak penghasilan yang dikenakan terhadap karyawan yang bekerja pada satu pemberi kerja merupakan pajak penghasilan:',NULL,NULL,'A')
;
INSERT INTO multiplechoice_question (jenis_soal,sulit,nomor,question,parent_nomor,multiplechoice_img_code,jawaban) VALUES 
('accounting',-1.96,21,'Tarif terendah pajak penghasilan untuk wajib pajak perorangan adalah:',NULL,NULL,'B')
,('accounting',-3.23,22,'Tarif pajak pertambahan nilai yang berlaku saat ini adalah:',NULL,NULL,'A')
,('accounting',1.66,23,'Metode penyusutan yang diperkenankan sesuai dengan undang-undang dan peraturan perpajakan yang berlaku saat ini adalah:',NULL,NULL,'B')
,('accounting',1.77,24,'Akun dalam kelompok “Aset”, misalnya Persediaan, biasanya memiliki saldo normal di posisi:',NULL,NULL,'C')
,('accounting',3.50,25,'Akun dalam kelompok “Liabilitas (Kewajiban)”, misalnya Utang Usaha, biasanya memiliki saldo normal di posisi:',NULL,NULL,'D')
,('accounting',2.33,26,'Akun dalam kelompok “Revenue”, misalnya Penjualan, biasanya memiliki saldo normal di posisi:',NULL,NULL,'C')
,('accounting',0.69,27,'Akun dalam kelompok “Beban”, misalnya Beban Gaji dan Tunjangan, biasanya memiliki saldo normal di posisi:',NULL,NULL,'B')
,('accounting',-2.35,28,'Perusahaan membeli bahan baku seharga Rp 100, PPN 10%, jangka waktu kredit 2 bulan. Jurnal yang benar jika pencatatan persediaan dilakukan dengan perpetual method adalah:',NULL,NULL,'C')
,('accounting',-2.08,29,'Apa yang dimaksud dengan nilai nominal saham?',NULL,NULL,'A-C')
,('accounting',0.26,30,'Lihat table di atas, berapakah nilai persediaan bahan baku XXX pada tanggal 31 Januari 2015 jika penilaiannya dilakukan dengan metode rata-rata (average method)?',NULL,'Tabel-soal-1','B-D')
;
INSERT INTO multiplechoice_question (jenis_soal,sulit,nomor,question,parent_nomor,multiplechoice_img_code,jawaban) VALUES 
('accounting',1.30,31,'Lihat table di atas, berapakah nilai persediaan bahan baku XXX pada tanggal 31 Januari 2015 jika penilaiannya dilakukan dengan metode masuk pertama keluar pertama (first in first out method)?',30,NULL,'C')
,('accounting',1.89,32,'Berikut ini adalah komponen biaya perolehan untuk persediaan barang jadi pada perusahaan yang bergerak dalam bidang manufaktur, kecuali :',NULL,NULL,'D')
,('accounting',-2.20,33,'Berikut ini adalah komponen biaya perolehan untuk persediaan bahan baku pada perusahaan yang bergerak dalam bidang manufaktur, kecuali :',NULL,NULL,'D')
,('accounting',2.17,34,'Laporan keuangan yang melaporkan Aset, Liabilitas (Kewajiban) dan Ekuitas pada suatu tanggal tertentu disebut:',NULL,NULL,'A')
,('accounting',-1.98,35,'Salah satu dari pernyataan berikut ini tentang “Accrual Basis of Accounting” adalah salah, yaitu:',NULL,NULL,'D')
,('accounting',-3.96,36,'Jika saldo persediaan pada awal tahun berjumlah Rp 600.000.000, jumlah pembelian dalam tahun berjalan berjumlah Rp 3.800.000.000 dan saldo persediaan pada akhir tahun berjumlah Rp 500.000.000, maka beban pokok penjualan akan menjadi:',NULL,NULL,'A')
,('accounting',1.89,37,'Jika pendapatan penjualan berjumlah Rp 4.000.000.000, beban pokok penjualan Rp 3.100.000.000 dan beban usaha Rp 600.000.000, maka laba bruto adalah:',NULL,NULL,'C')
,('accounting',1.66,38,'Pada tanggal 31 Desember 2015  PT ABC mempunyai total aset sebesar Rp 350.000.000.000 dan ekuitas sebesar Rp 150.000.000.000, maka jumlah liabilitas (kewajiban) adalah sebesar:',NULL,NULL,'A')
,('accounting',-3.40,39,'Di neraca, Aset Lancar (Current Assets) biasanya disusun menurut urutan:',NULL,NULL,'B')
,('auditing',1.51,1,'Tujuan audit atas laporan keuangan yang dilakukan oleh auditor independen (akuntan publik) pada umumnya adalah untuk:',NULL,NULL,'D')
;
INSERT INTO multiplechoice_question (jenis_soal,sulit,nomor,question,parent_nomor,multiplechoice_img_code,jawaban) VALUES 
('auditing',0.31,2,'Laporan keuangan yang telah diaudit oleh auditor independen (akuntan publik) merupakan tanggung jawab dari:',NULL,NULL,'C')
,('auditing',2.46,3,'Laporan keuangan yang disusun oleh manajemen perusahaan harus disajikan sesuai dengan:',NULL,NULL,'D')
,('auditing',-0.74,4,'Dari bukti-bukti di bawah ini yang merupakan bukti paling kompeten adalah:',NULL,NULL,'C')
,('auditing',1.29,5,'Audit yang dilakukan oleh auditor independen (akuntan publik) harus dilaksanakan sesuai dengan:',NULL,NULL,'B')
,('auditing',-2.75,6,'Meskipun jumlah, jenis dan isi kertas kerja bisa bervariasi sesuai dengan kebutuhan, tetapi kertas kerja harus mencakup:',NULL,NULL,'D')
,('auditing',1.58,7,'Dalam mengerjakan kertas kerja, auditor harus ingat bahwa:',NULL,NULL,'B')
,('auditing',2.34,8,'Teman Anda, Bunga Cindy Lestari (BCL) sedang mengaudit akun kas & bank pada PT ABC dan akan mengirimkan permintaan konfirmasi kepada Bank Central Asia. Untuk menghemat perangko, accounting manager PT ABC meminta agar konfirmasi bank tersebut dikirimkan sendiri oleh staff PT ABC karena lokasi Bank Central Asia terletak persis di sebelah kantor PT ABC. Setelah berpikir sejenak, BCL mengabulkan permintaan accounting manager PT ABC tersebut. Menurut Anda, apakah keputusan BCL tersebut benar?',NULL,NULL,'C')
,('auditing',1.78,9,'Formulir permintaan konfirmasi bank harus di tanda tangani oleh Authorized Signature yaitu:',NULL,NULL,'D')
,('auditing',-0.39,10,'Teman Anda, Luna Mayangsari, sedang melakukan test atas asuransi aset tetap pada PT ZZZ dan mendapatkan data-data sebagai berikut :',NULL,NULL,'A')
,('auditing',1.45,11,'Siapakah yang bertanggung jawab untuk melakukan pemeriksaan fisik atas persediaan (stocktaking) pada setiap akhir tahun?',NULL,NULL,'A')
;
INSERT INTO multiplechoice_question (jenis_soal,sulit,nomor,question,parent_nomor,multiplechoice_img_code,jawaban) VALUES 
('auditing',-2.55,12,'Apa yang harus dilakukan oleh seorang auditor pada saat klien melakukan pemeriksaan fisik atas persediaan (stocktaking) pada setiap akhir tahun?',NULL,NULL,'D')
,('auditing',-0.04,13,'Konfirmasi piutang usaha yang harus dijawab oleh pelanggan apabila saldonya cocok maupun tidak cocok, disebut dengan istilah :',NULL,NULL,'D')
,('auditing',-1.77,14,'Teman Anda, Avgun, sedang mengaudit akun piutang usaha PT Terima Kasih Cinta Trading. Karena jadual yang ketat, Avgun memutuskan agar jawaban konfirmasi piutang usaha dari para pelanggan PT TKC Trading diminta dikirimkan via fax ke KAP ZYZ & Rekan agar lebih cepat diterima. Setujukah Anda dengan keputusan Avgun tersebut?',NULL,NULL,'D')
,('auditing',0.37,15,'Yang bertanggung jawab atas penyusunan laporan keuangan yang kita audit adalah :',NULL,NULL,'D')
,('auditing',1.24,16,'Auditor independen akan memberikan Unqualified Opinion jika salah satu kondisi di bawah ini terpenuhi:',NULL,NULL,'A')
,('auditing',0.43,17,'Auditor independen akan memberikan Adverse Opinion jika salah satu kondisi di bawah ini terpenuhi:',NULL,NULL,'A')
,('auditing',-0.57,18,'Auditor independen akan memberikan Qualified Opinion jika salah satu kondisi di bawah ini terpenuhi:',NULL,NULL,'A')
,('auditing',0.52,19,'Auditor independen akan memberikan Disclaimer Opinion jika salah satu kondisi di bawah ini terpenuhi:',NULL,NULL,'A')
,('auditing',0.73,20,'Manakah dari prosedur-prosedur di bawah ini yang paling meyakinkan bagi akuntan di dalam memperoleh bukti audit tentang adanya persediaan-persediaan? ',NULL,NULL,'D')
,('auditing',-4.13,21,'Standar audit  menyatakan bahwa audit harus dilaksanakan oleh seorang atu lebih yang memiliki keahlian dan pelatihan teknis yang cukup sebagai auditor. Hal ini mengharuskan seorang auditor untuk:',NULL,NULL,'B')
;
INSERT INTO multiplechoice_question (jenis_soal,sulit,nomor,question,parent_nomor,multiplechoice_img_code,jawaban) VALUES 
('auditing',-2.24,22,'Standar audit menyatakan bahwa dalam semua hal yang berhubungan dengan perikatan, independensi dalam sikap mental harus dipertahankan oleh auditor. Hal ini mengharuskan seorang auditor untuk:',NULL,NULL,'A')
,('auditing',1.94,23,'Standar audit  menyatakan bahwa dalam pelaksanaan audit dan penyusunan laporannya, auditor wajib menggunakan kemahiran profesionalnya dengan cermat dan seksama. Hal ini mengharuskan seorang auditor untuk:',NULL,NULL,'A')
,('auditing',0.09,24,'Alasan (tujuan) utama seorang auditor independen mengumpulkan (memperoleh) bukti-bukti audit kompeten yang cukup adalah untuk:',NULL,NULL,'A')
,('auditing',0.22,25,'Tanggung jawab utama untuk kecukupan pengungkapan dalam laporan keuangan terletak pada:',NULL,NULL,'B')
,('auditing',1.45,26,'Jenis bukti audit yang paling dapat diandalkan yang seorang auditor dapat peroleh adalah:',NULL,NULL,'B')
,('auditing',0.43,27,'Tujuan utama auditor memahami dan mengevaluasi pengendalian intern klien adalah:',NULL,NULL,'A')
,('auditing',-1.87,28,'Dari pernyataan di bawah ini, mana yang paling tepat menjelaskan tujuan dari prosedur audit:',NULL,NULL,'C')
,('auditing',0.31,29,'Auditor kemungkinan besar akan melakukan tes ekstensif untuk kemungkinan kurang saji (possible understatement) pada akun:',NULL,NULL,'A')
,('auditing',-0.70,30,'Auditor kemungkinan besar akan melakukan tes ekstensif untuk kemungkinan lebih saji (possible overstatement) pada akun:',NULL,NULL,'A')
,('auditing',1.58,31,'Besaran dan sifat dari suatu salah saji yang dapat mengakibatkan keputusan dari pengguna laporan keuangan berubah atau terpengaruh sebagai akibat dari salah saji tersebut disebut :',NULL,NULL,'D')
;
INSERT INTO multiplechoice_question (jenis_soal,sulit,nomor,question,parent_nomor,multiplechoice_img_code,jawaban) VALUES 
('auditing',1.71,32,'Representasi oleh manajemen yang melekat pada komponen-komponen dari laporan keuangan disebut :',NULL,NULL,'A')
,('auditing',-2.88,33,'Berikut ini adalah jenis-jenis Audit Assertions, kecuali :',NULL,NULL,'D')
,('auditing',0.84,34,'Suatu prosedur audit yang dilakukan dengan tujuan utama yang diarahkan untuk menguji validitas suatu asersi dari akun neraca atau akun laba rugi disebut :',NULL,NULL,'C')
,('auditing',-2.98,35,'Untuk memeriksa dan meyakinkan keberadaan (existence) saldo akun piutang usaha, maka auditor melakukan prosedur audit:',NULL,NULL,'D')
,('auditing',-1.80,36,'Untuk memeriksa dan meyakinkan keberadaan (existence) saldo akun persediaan, maka auditor melakukan prosedur audit:',NULL,NULL,'A')
,('auditing',1.78,37,'Apa kepanjangan dari CPA?',NULL,NULL,'A')
,('auditing',0.11,38,'Jasa asurans yang diberikan akuntan publik berupa perikatan asurans yang diterapkan atas informasi keuangan historis yang bertujuan untuk memberikan keyakinan memadai atas  kewajaran penyajian informasi keuangan historis tersebut dan kesimpulannya dinyatakan dalam bentuk pernyataan positif disebut sebagai:',NULL,NULL,'B')
,('auditing',-1.44,39,'Jasa asurans yang diberikan akuntan publik berupa perikatan asurans yang diterapkan atas informasi keuangan historis yang bertujuan untuk memberikan keyakinan terbatas atas  kewajaran penyajian informasi keuangan historis tersebut dan kesimpulannya dinyatakan dalam bentuk pernyataan negatif disebut sebagai:',NULL,NULL,'B')
,('english',-0.39,1,'When the contracts  _________  ready, have them sent to the purchasers.',NULL,NULL,'C')
,('english',-1.69,2,'The   ___________  of the new building will start next month.',NULL,NULL,'B')
;
INSERT INTO multiplechoice_question (jenis_soal,sulit,nomor,question,parent_nomor,multiplechoice_img_code,jawaban) VALUES 
('english',-1.69,3,'The stapler is  _____  the desk.',NULL,NULL,'A')
,('english',1.79,4,'Mr. Sylvester delivered the  ___________  bid to the client.',NULL,NULL,'D')
,('english',0.01,5,'If your flight is delayed, ____________ me from the airport.',NULL,NULL,'C')
,('english',0.81,6,'The airport taxes are ____________  in the ticket price.',NULL,NULL,'D')
,('english',-0.37,7,'Mr. Nash wants to  __________ the costs by tonight',NULL,NULL,'B')
,('english',-0.93,8,'A computer is ______________  than a typewriter',NULL,NULL,'A')
,('english',-0.31,9,'Mr. Flint is the person ___________  orders office supplies',NULL,NULL,'C')
,('english',0.42,10,'The Judge’s analysis is due __________  Friday',NULL,NULL,'D')
,('english',-0.19,11,'New paint  ________  pictures will make the office look better.',NULL,NULL,'B')
,('english',-0.31,12,'Everyone is  __________  that Ms. Hidayati seldom leaves before 6.30.',NULL,NULL,'A')
;
INSERT INTO multiplechoice_question (jenis_soal,sulit,nomor,question,parent_nomor,multiplechoice_img_code,jawaban) VALUES 
('english',0.50,13,'The itinerary  _________ with the cruise list.',NULL,NULL,'B')
,('english',-1.06,14,'Passengers can check in for the charter flight  _________  08.00 and 12.00 tomorrow.',NULL,NULL,'A')
,('english',3.09,15,'The President has his travel agent  ___________  the reservation.',NULL,NULL,'C')
,('english',-0.10,16,'It is  ___________  to transfer a document by e-mail than by fax.',NULL,NULL,'D')
,('english',0.89,17,'Mr. Doughterty typed the speech, ______________  Ms. Nyro prepared the charts.',NULL,NULL,'B')
,('english',2.59,18,'The head of the porters  ______________  guests with their luggage.',NULL,NULL,'C')
,('english',-1.19,19,'Ask the account receivable clerk  _________  the invoice.',NULL,NULL,'A')
,('english',-1.10,20,'An administrative assistant keeps an office running _______________',NULL,NULL,'D')
,('english',-0.10,21,'Each passenger’s name  __________ with his or her cabin number.',NULL,NULL,'C')
,('english',1.95,22,'The manager got his staff  ___________  last weekend.',NULL,NULL,'A')
;
INSERT INTO multiplechoice_question (jenis_soal,sulit,nomor,question,parent_nomor,multiplechoice_img_code,jawaban) VALUES 
('english',2.55,23,'The variety of insurance benefits  ___________  very broad under this policy.',NULL,NULL,'B')
,('english',-1.29,24,'The directory lists each passenger’s name  ________________  address',NULL,NULL,'A')
,('english',0.69,25,'Please leave your luggage  __________  the bus for loading',NULL,NULL,'D')
,('english',-1.15,26,'Mr. Crocker will return your call  ________  he arrives',NULL,NULL,'C')
,('english',-0.60,27,'If product were not safe, we  ______________  it.',NULL,NULL,'D')
,('english',0.17,28,'The cruise handbook  ______________  all ship policies.',NULL,NULL,'A')
,('english',0.74,29,'_____________  cost make profits smaller.',NULL,NULL,'C')
,('english',-2.26,30,'Mr. Dortmunder  ____________  for meetings',NULL,NULL,'B')
,('english',0.32,31,'________________  we had checked the figures, the supervisor found a mistake.',NULL,NULL,'D')
,('english',-0.93,32,'Mr. Woodward wants to make  __________________.',NULL,NULL,'C')
;
INSERT INTO multiplechoice_question (jenis_soal,sulit,nomor,question,parent_nomor,multiplechoice_img_code,jawaban) VALUES 
('english',1.25,33,'The financial team  ____________  that the offer was rejected.',NULL,NULL,'A')
,('english',2.63,34,'A record of complaints  _________ kept in the purser’s office.',NULL,NULL,'B')
,('english',-0.46,35,'The only difference  _______________  the two flights is time of departure.',NULL,NULL,'C')
,('english',-0.02,36,'___________ Ms. Veres was late; she did not miss the performance.',NULL,NULL,'D')
,('english',0.74,37,'Mr. Still was responsible for  ____________  the data.',NULL,NULL,'B')
,('english',2.25,38,'The company  ____________  spouses of employees in the invitation to the banquet.',NULL,NULL,'C')
,('english',2.87,39,'Ms. Bassey has suggested  ______________  more reservation clerks.',NULL,NULL,'B')
,('english',-2.16,40,'The meeting will be held  __________  Friday.',NULL,NULL,'D')
,('english',-0.97,41,'If the delivery is late, we  __________  the spinning charges.',NULL,NULL,'B')
,('english',-1.69,42,'We cannot process the order  ____________  we get a copy of the purchase order.',NULL,NULL,'C')
;
INSERT INTO multiplechoice_question (jenis_soal,sulit,nomor,question,parent_nomor,multiplechoice_img_code,jawaban) VALUES 
('english',-0.97,43,'The visitors will be arriving  ______  the office in twenty minutes.',NULL,NULL,'A')
,('english',0.84,44,'Please use the  _____________  envelope for your reply.',NULL,NULL,'D')
,('english',0.96,45,'Mr. Morton depends on his assistants for  ______________.',NULL,NULL,'C')
,('english',-0.97,46,'The package should arrive  ______________  Thursday.',NULL,NULL,'B')
,('english',0.52,47,'The newspaper expects circulation  _____________  next year.',NULL,NULL,'B')
,('english',-1.10,48,'Using a checklist is an  _______________  way to make plans.',NULL,NULL,'A')
,('english',-2.75,49,'The food has been ordered, _____  it has not arrived',NULL,NULL,'D')
;
