INSERT INTO multiplechoice_choices (multiplechoice_question_id,choice,label) VALUES 
(1,'A',' Laporan posisi keuangan dan Laporan laba rugi dan penghasilan komprehensif lain')
,(1,'B','Laporan posisi keuangan, Laporan laba rugi dan penghasilan komprehensif lain, dan Catatan atas laporan keuangan')
,(1,'C','Laporan posisi keuangan, Laporan laba rugi dan penghasilan komprehensif lain, Laporan Perubahan Ekuitas dan Catatan atas laporan keuangan')
,(1,'D','Laporan posisi keuangan, Laporan laba rugi dan penghasilan komprehensif lain, Laporan Perubahan Ekuitas, Laporan Arus Kas dan Catatan atas laporan keuangan')
,(2,'A','Beban pokok penjualan')
,(2,'B','Beban penjualan')
,(2,'C','Beban upah langsung')
,(2,'D','Beban umum dan administrasi')
,(3,'A',' Pemegang saham mayoritas')
,(3,'B','Pemegang saham minoritas')
;
INSERT INTO multiplechoice_choices (multiplechoice_question_id,choice,label) VALUES 
(3,'C','Kreditur (Bank)')
,(3,'D','Pemasok')
,(4,'A','Dr Pembelian Rp 110, Cr Utang usaha Rp 110')
,(4,'B','Dr Pembelian Rp 100, Cr Utang usaha Rp 100')
,(4,'C','Dr Pembelian Rp 100, Dr PPN Rp 10, Cr Utang usaha Rp 110')
,(4,'D','Dr Pembelian Rp 110,  Cr PPN Rp 10, Cr Utang usaha Rp 100')
,(5,'A','Dr Biaya harus dibayar Rp 250,  Cr Beban usaha Rp 250')
,(5,'B','Dr Beban usaha Rp 250, Cr Biaya harus dibayar Rp 250')
,(5,'C',' Dr Kas dan bank Rp 250,  Cr Beban usaha Rp 250')
,(5,'D','Dr Beban usaha Rp 250,  Cr Kas dan bank Rp 250')
;
INSERT INTO multiplechoice_choices (multiplechoice_question_id,choice,label) VALUES 
(6,'A','Dr Kas dan bank Rp 108, Dr Potongan pembelian Rp 2, Cr Utang usaha Rp 11')
,(6,'B','Dr Kas dan bank Rp 110, Cr Potongan pembelian Rp 2, Cr Utang usaha Rp 108')
,(6,'C',' Dr Utang usaha Rp 108, Dr Potongan pembelian Rp 2, Cr Kas dan bank Rp 110')
,(6,'D','Dr Utang usaha Rp 110, Cr Potongan pembelian Rp 2, Cr Kas dan bank Rp 108')
,(7,'A','Jumlah aset lancar dibagi dengan jumlah liabilitas jangka pendek')
,(7,'B','Jumlah liabilitas dibagi dengan jumlah ekuitas')
,(7,'C','Jumlah aset tetap dibagi dengan liabilitas jangka panjang')
,(7,'D','Jumlah aset dibagi dengan jumlah liabilitas')
,(8,'A','Laba kotor dibagi dengan penjualan dikalikan dengan 100%')
,(8,'B','Laba kotor dibagi dengan penjualan')
;
INSERT INTO multiplechoice_choices (multiplechoice_question_id,choice,label) VALUES 
(8,'C','Penjualan dibagi dengan saldo piutang rata-rata')
,(8,'D','Penjualan dibagi dengan saldo piutang rata-rata dikalikan dengan 100%')
,(9,'A','Pasal 29')
,(9,'B','Pasal 25')
,(9,'C','Pasal 24')
,(9,'D','Pasal 23')
,(10,'A','Pasal 29')
,(10,'B','Pasal 25')
,(10,'C','Pasal 24')
,(10,'D','Pasal 23')
;
INSERT INTO multiplechoice_choices (multiplechoice_question_id,choice,label) VALUES 
(11,'A','25% dari laba kena pajak')
,(11,'B','30% dari laba kena pajak')
,(11,'C','35% dari laba kena pajak')
,(11,'D','20% dari laba kena pajak')
,(12,'A','Straight line method')
,(12,'B','First in first out method')
,(12,'C','Average method')
,(12,'D','b dan c keduanya benar')
,(13,'A','Piutang usaha')
,(13,'B','Persediaan barang jadi')
;
INSERT INTO multiplechoice_choices (multiplechoice_question_id,choice,label) VALUES 
(13,'C','Aset tetap')
,(13,'D','Modal saham')
,(14,'A','Pemakaian bahan baku dan pembantu')
,(14,'B','Upah langsung')
,(14,'C','Retur pembelian')
,(14,'D','Retur penjualan')
,(15,'A','Dr Piutang usaha Rp 110, Cr Penjualan Rp 110')
,(15,'B','Dr Piutang usaha Rp 100, Cr Penjualan Rp 100')
,(15,'C',' Dr Piutang usaha Rp 100, Dr PPN Rp 10, Cr Penjualan Rp 110')
,(15,'D','Dr Piutang usaha Rp 110, Cr PPN Rp 10, Cr Penjualan Rp 100')
;
INSERT INTO multiplechoice_choices (multiplechoice_question_id,choice,label) VALUES 
(16,'A','Dr Beban pokok penjualan Rp 150, Cr Akumulasi penyusutan mesin Rp 150')
,(16,'B','Dr Akumulasi penyusutan mesin Rp 150, Cr Beban pokok penjualan Rp 150')
,(16,'C','Dr Beban pokok penjualan Rp 150, Cr mesin-mesin fabrik Rp 150')
,(16,'D','Dr Mesin-mesin fabrik Rp 150, Cr Beban pokok penjualan Rp 150')
,(17,'A','Dr Kas dan bank Rp 108, Dr Potongan penjualan Rp 2, Cr Piutang usaha Rp 110')
,(17,'B','Dr Kas dan bank Rp 110, Cr Potongan penjualan Rp 2, Cr Piutang usaha Rp 108')
,(17,'C',' Dr Piutang usaha Rp 108, Dr Potongan penjualan Rp 2, Cr Kas dan bank Rp 110')
,(17,'D','Dr Piutang usaha Rp 110, Cr Potongan penjualan Rp 2, Cr Kas dan bank Rp 108')
,(18,'A','Jumlah aset lancar dibagi dengan jumlah liabilitas jangka pendek X 100%')
,(18,'B','Jumlah liabilitas dibagi dengan jumlah ekuitas X 100%')
;
INSERT INTO multiplechoice_choices (multiplechoice_question_id,choice,label) VALUES 
(18,'C','Jumlah aset tetap dibagi dengan liabilitas jangka panjang X 100%')
,(18,'D','Jumlah aset dibagi dengan jumlah kewajiban X 100%')
,(19,'A','Laba bruto dibagi dengan penjualan dikalikan dengan 100%')
,(19,'B','Laba bruto dibagi dengan penjualan')
,(19,'C','Penjualan dibagi dengan saldo piutang rata-rata ')
,(19,'D','Penjualan dibagi dengan saldo piutang rata-rata dikalikan dengan 100%')
,(20,'A','Pasal 25')
,(20,'B','Pasal 24')
,(20,'C','Pasal 23')
,(20,'D','Pasal 21')
;
INSERT INTO multiplechoice_choices (multiplechoice_question_id,choice,label) VALUES 
(21,'A','5% untuk jumlah Rp 25.000.000 pertama')
,(21,'B','5% untuk jumlah Rp 50.000.000 pertama')
,(21,'C','5% untuk jumlah Rp 100.000.000 pertama')
,(21,'D','5% untuk jumlah Rp 200.000.000 pertama')
,(22,'A','10% dari harga jual ')
,(22,'B','10% dari (harga jual – harga beli)')
,(22,'C','10% dari laba bruto')
,(22,'D','10% dari nilai ekspor')
,(23,'A','Straight line method')
,(23,'B','First in first out method')
;
INSERT INTO multiplechoice_choices (multiplechoice_question_id,choice,label) VALUES 
(23,'C','Average method')
,(23,'D','b dan c keduanya benar')
,(24,'A','Debet')
,(24,'B','Kredit')
,(24,'C','Tergantung kondisi (bisa Debet atau bisa Kredit)')
,(24,'D','a dan b keduanya benar')
,(25,'A','Debet')
,(25,'B','Kredit')
,(25,'C','Tergantung kondisi (bisa Debet atau bisa Kredit)')
,(25,'D','a dan b keduanya benar')
;
INSERT INTO multiplechoice_choices (multiplechoice_question_id,choice,label) VALUES 
(26,'A','Debet')
,(26,'B','Kredit')
,(26,'C','Tergantung kondisi (bisa Debet atau bisa Kredit)')
,(26,'D','a dan b keduanya benar')
,(27,'A','Debet')
,(27,'B','Kredit')
,(27,'C','Tergantung kondisi (bisa Debet atau bisa Kredit)')
,(27,'D','a dan b keduanya benar')
,(28,'A','Dr Persediaan Rp 110, Cr Utang usaha Rp 110')
,(28,'B','Dr Persediaan Rp 100, Cr Utang usaha Rp 100')
;
INSERT INTO multiplechoice_choices (multiplechoice_question_id,choice,label) VALUES 
(28,'C','  Dr Persediaan Rp 100, Dr PPN Rp 10  ')
,(28,'D',' Dr Persediaan Rp 110, Cr PPN Rp 10, Cr Utang usaha Rp 100')
,(29,'A','Nilai yang tercantum dalam surat saham')
,(29,'B','Nilai saham pada saat dibeli')
,(29,'C','  Nilai saham pada saat dijual')
,(29,'D','Nilai yang tercantum dalam akta notaris')
,(30,'A','4500000')
,(30,'B','4300000')
,(30,'C','  Rp 4.200.000')
,(30,'D','4100000')
;
INSERT INTO multiplechoice_choices (multiplechoice_question_id,choice,label) VALUES 
(31,'A','4500000')
,(31,'B','4300000')
,(31,'C','4200000')
,(31,'D','4100000')
,(32,'A','Biaya iklan')
,(32,'B','Pemakaian bahan baku dan pembantu')
,(32,'C','Upah langsung')
,(32,'D',' Beban produksi tak langsung (factory overhead)')
,(33,'A','Harga beli')
,(33,'B','Potongan pembelian')
;
INSERT INTO multiplechoice_choices (multiplechoice_question_id,choice,label) VALUES 
(33,'C','Biaya angkutan')
,(33,'D','Upah langsung')
,(34,'A','Laporan laba rugi dan penghasilan komprehensif lain')
,(34,'B','Laporan perubahan ekuitas')
,(34,'C','Laporan posisi keuangan (neraca)')
,(34,'D','Laporan arus kas')
,(35,'A','Peristiwa yang mempengaruhi laporan keuangan perusahaan adalah dicatat pada periode dimana peristiwa tersebut terjadi')
,(35,'B','Pendapatan diakui pada periode dimana pendapatan tersebut dihasilkan')
,(35,'C','Basis adalah sesuai dengan standar akuntansi keuangan')
,(35,'D','Pendapatan dicatat hanya jika kas telah diterima dan Beban dicatat hanya jika telah dibayar')
;
INSERT INTO multiplechoice_choices (multiplechoice_question_id,choice,label) VALUES 
(36,'A','3900000000')
,(36,'B','3700000000')
,(36,'C','3300000000')
,(36,'D','4200000000')
,(37,'A','300000000')
,(37,'B','900000000')
,(37,'C','3400000000')
,(37,'D','4000000000')
,(38,'A','150000000000')
,(38,'B','200000000000')
;
INSERT INTO multiplechoice_choices (multiplechoice_question_id,choice,label) VALUES 
(38,'C','500000000000')
,(38,'D','350000000000')
,(39,'A','Jatuh tempo')
,(39,'B','Likuiditas')
,(39,'C','Alphabet')
,(39,'D','Signifikansi')
,(40,'A','Memberikan opini tentang kewajaran, dalam semua hal yang material, laporan keuangan klien')
,(40,'B','Memberikan opini tentang kebenaran, dalam semua hal yang material, laporan keuangan klien')
,(40,'C','Memberikan opini tentang kewajaran, dalam semua hal yang material, laporan keuangan klien sesuai dengan standar akuntansi keuangan yang berlaku di Indonesia')
,(40,'D','Memberikan opini tentang kebenaran, dalam semua hal yang material, laporan keuangan klien sesuai dengan standar akuntansi keuangan yang berlaku di Indonesia')
;
INSERT INTO multiplechoice_choices (multiplechoice_question_id,choice,label) VALUES 
(41,'A','Manajemen perusahaan')
,(41,'B','Pemegang saham perusahaan')
,(41,'C','Auditor independen')
,(41,'D','Akuntan publik')
,(42,'A','Standar Akuntansi Keuangan yang ditetapkan Institut Akuntan Publik Indonesia (IAPI)')
,(42,'B','Standar Akuntansi Keuangan yang ditetapkan Ikatan Akuntan Indonesia')
,(42,'C','Standar Auditing yang ditetapkan Institut Akuntan Publik Indonesia (IAPI)')
,(42,'D','Standar Auditing yang ditetapkan Ikatan Akuntan Indonesia (IAI)')
,(43,'A','Faktur penjualan')
,(43,'B','Perhitungan yang disebut secara independen oleh auditor mengenai earning per share')
;
INSERT INTO multiplechoice_choices (multiplechoice_question_id,choice,label) VALUES 
(43,'C','Bank statement')
,(43,'D','Letter of representation yang dibuat oleh kontroler perusahaan klien')
,(44,'A','Standar Akuntansi Keuangan yang ditetapkan Institut Akuntan Publik Indonesia (IAPI)')
,(44,'B','Standar Akuntansi Keuangan yang ditetapkan Ikatan Akuntan Indonesia')
,(44,'C','Standar Audit yang ditetapkan Institut Akuntan Publik Indonesia (IAPI)')
,(44,'D','Standar Audit yang ditetapkan Ikatan Akuntan Indonesia (IAI)')
,(45,'A','Salinan dari catatan-catatan klien yang telah diperiksa auditor selama pemeriksaan')
,(45,'B','Penilaian tentang efisiensi dankompetensi asisten-asisten yang digunakan dalam pemeriksaan yang dilakukan oleh partner penanggung jawab pemeriksaan')
,(45,'C','Komentar akuntansi tentang efisiensi dan kompetensi personel perusahaan klien')
,(45,'D','Prosedur-prosedur pemeriksaan yang telah diikuti dan test-test yang telah dilakukan di dalam mendapatkan bukti ')
;
INSERT INTO multiplechoice_choices (multiplechoice_question_id,choice,label) VALUES 
(46,'A','Kertas kerja harus mendukung opini atas laporan keuangan yang diperiksa')
,(46,'B','Kertas kerja adalah milik klien')
,(46,'C','Kertas kerja harus dirancang sehingga dapat memenuhi kebutuhan auditor dalam setiap pemeriksaan')
,(46,'D','Kertas kerja harus dipandang sebagai pengganti catatan-catatan klien')
,(47,'A','Benar, untuk efisiensi')
,(47,'B','Benar, karena PT ABC adalah klien lama dan dapat dipercaya')
,(47,'C','Benar, karena Anda tahu lokasi Bank Central Asia memang persis di sebelah kantor PT ABC')
,(47,'D','Salah, karena seharusnya konfirmasi langsung dikirimkan oleh auditor (bukan oleh klien) ')
,(48,'A','Direksi')
,(48,'B','Direksi/Pejabat perusahaan yang mempunyai wewenang untuk menandatangani giro/cheuque ')
;
INSERT INTO multiplechoice_choices (multiplechoice_question_id,choice,label) VALUES 
(48,'C','Accounting Manager')
,(48,'D','Finance Manager')
,(49,'A','Mengusulkan audit adjustment untuk menurunkan nilai buku aset tetap karena ternyata setelah diselidiki terdapat aset tetap yang tidak diasuransikan')
,(49,'B','Memasukkan hal tersebut dalam Management Letter dengan mengusulkan agar seluruh aset tetap PT ZZZ diasuransikan')
,(49,'C','Tidak perlu mengusulkan audit adjustment')
,(49,'D','Tidak perlu membuat Management Letter')
,(50,'A','Audit Assistant')
,(50,'B','Auditor Independen')
,(50,'C','Audit Manager')
,(50,'D','Manajemen Klien')
;
INSERT INTO multiplechoice_choices (multiplechoice_question_id,choice,label) VALUES 
(51,'A','Mengunjungi stocktaking tersebut dan melakukan observasi untuk memastikan stocktaking telah dilakukan dengan prosedur yang baik.')
,(51,'B','Secara sampling, melakukan perhitungan atas persediaan barang tertentu dan mencocokkannya dengan kartu stock')
,(51,'C','Memeriksa bukti-bukti penerimaan dan pengeluaran barang yang terjadi sebelum dan pada saat tanggal stocktaking')
,(51,'D','A,B dan C semuanya benar')
,(52,'A','Konfirmasi positif')
,(52,'B','Konfirmasi negatif')
,(52,'C','Konfirmasi wajib jawab')
,(52,'D','Konfirmasi piutang')
,(53,'A','Setuju karena jawaban konfirmasi akan lebih cepat diterima jika via fax')
,(53,'B','Setuju apabila kita yakin bahwa fax tersebut dikirimkan langsung oleh pelanggan PT TKC Trading')
;
INSERT INTO multiplechoice_choices (multiplechoice_question_id,choice,label) VALUES 
(53,'C','Tidak setuju karena fax bukan merupakan audit evidence yang sah')
,(53,'D','Setuju apabila jawaban konfirmasi yang ASLI juga dikirimkan menyusul via post ke KAP ZYZ & Rekan')
,(54,'A','Audit Assistant')
,(54,'B','Audit Manager')
,(54,'C','Manajemen klien')
,(54,'D','Auditor Independen')
,(55,'A','Terdapat pembatasan ruang lingkup audit tetapi dampaknya tidak material')
,(55,'B','Ketidakberhasilan auditor untuk memperoleh bukti audit yang cukup')
,(55,'C','Laporan keuangan secara keseluruhan tidak disajikan secara wajar sesuai dengan standar akuntansi keuangan di Indonesia')
,(55,'D','Laporan keuangan, dalam semua hal yang material, telah disajikan secara wajar sesuai dengan standar akuntansi keuangan di Indonesia')
;
INSERT INTO multiplechoice_choices (multiplechoice_question_id,choice,label) VALUES 
(56,'A','Terdapat pembatasan ruang lingkup audit tetapi dampaknya tidak material')
,(56,'B','Ketidakberhasilan auditor untuk memperoleh bukti audit yang cukup')
,(56,'C','Laporan keuangan secara keseluruhan tidak disajikan secara wajar sesuai dengan prinsip akuntansi yang berlaku umum di Indonesia')
,(56,'D','Laporan keuangan, dalam semua hal yang material, telah disajikan secara wajar sesuai dengan standar akuntansi keuangan di Indonesia')
,(57,'A','Terdapat pembatasan ruang lingkup audit tetapi dampaknya tidak material')
,(57,'B','Ketidakberhasilan auditor untuk memperoleh bukti audit yang cukup')
,(57,'C','Laporan keuangan secara keseluruhan tidak disajikan secara wajar sesuai dengan standar akuntansi keuangan di Indonesia')
,(57,'D','Laporan keuangan, dalam semua hal yang material, telah disajikan secara wajar sesuai dengan standar akuntansi keuangan di Indonesia')
,(58,'A','Terdapat pembatasan ruang lingkup audit tetapi dampaknya tidak material')
,(58,'B','Ketidakberhasilan auditor untuk memperoleh bukti audit yang cukup')
;
INSERT INTO multiplechoice_choices (multiplechoice_question_id,choice,label) VALUES 
(58,'C','Laporan keuangan secara keseluruhan tidak disajikan secara wajar sesuai dengan standar akuntansi keuangan di Indonesia')
,(58,'D','Laporan keuangan, dalam semua hal yang material, telah disajikan secara wajar sesuai dengan standar akuntansi keuangan di Indonesia')
,(59,'A','Observasi perhitungan fisik persediaan')
,(59,'B','Pernyataan tertulis tentang persediaan dari manajemen')
,(59,'C','Konfirmasi tentang persediaan yang ada di gudang sewaan')
,(59,'D','Perhitungan kembali yang dilakukan akuntan')
,(60,'A','Memiliki kemampuan dalam bidang bisnis dan keuangan')
,(60,'B','Memiliki pendidikan dalam bidang akuntansi dan auditing serta memiliki pengalaman dan pelatihan yang cukup dalam bidang-bidang tersebut')
,(60,'C','Memiliki keahlian dalam bidang teknologi informasi')
,(60,'D','Memiliki kemampuan dalam perencanaan dan supervisi')
;
INSERT INTO multiplechoice_choices (multiplechoice_question_id,choice,label) VALUES 
(61,'A','Observasi perhitungan fisik persediaan')
,(61,'B','Pernyataan tertulis tentang persediaan dari manajemen')
,(61,'C','Konfirmasi tentang persediaan yang ada di gudang sewaan')
,(61,'D','Perhitungan kembali yang dilakukan akuntan')
,(62,'A','Tidak mudah dipengaruhi')
,(62,'B','Melaksanakan skeptisme professional')
,(62,'C','Harus selalu mengganggap bahwa manajemen klien adalah tidak jujur')
,(62,'D','Mampu bekerja sendiri tanpa supervisi atasannya')
,(63,'A','Mendeteksi kecurangan (fraud)')
,(63,'B','Mengevaluasi manajemen')
;
INSERT INTO multiplechoice_choices (multiplechoice_question_id,choice,label) VALUES 
(63,'C','Sebagai dasar memadai untuk meyatakan pendapat')
,(63,'D','Menentukan risiko audit')
,(64,'A','Partner')
,(64,'B','Auditor In Charge')
,(64,'C','Audit staff')
,(64,'D','Manajemen klien')
,(65,'A','Pemeriksaan fisik oleh auditor')
,(65,'B','Perhitungan oleh auditor dari catatan-catatan perusahaan')
,(65,'C','Konfirmasi yang langsung diterima dari pihak ke tiga')
,(65,'D','Dokumen dari pihak eksternal')
;
INSERT INTO multiplechoice_choices (multiplechoice_question_id,choice,label) VALUES 
(66,'A','Memberikan saran-saran yang membangun untuk peningkatan pengendalian intern klien')
,(66,'B','Untuk merencanakan audit dan menentukan sifat, saat dan lingkup pengujian yang akan dilakukan')
,(66,'C','Untuk menyatakan pendapat')
,(66,'D','Untuk menentukan prosedur dan catatan yang berkaitan dengan pengamanan aset klien')
,(67,'A','Untuk mendeteksi kesalahan atau kecurangan')
,(67,'B','Untuk mematuhi standar akuntansi keuangan yang berlaku')
,(67,'C','Untuk memperoleh keyakinan memadai tentang apakah laporan keuangan secara keseluruhan bebas dari salah saji material')
,(67,'D','Untuk menverifikasi keakuratan saldo-saldo akun')
,(68,'A','Pendapatan')
,(68,'B','Aset')
;
INSERT INTO multiplechoice_choices (multiplechoice_question_id,choice,label) VALUES 
(68,'C','Liabilitas')
,(68,'D','Biaya')
,(69,'A','Pendapatan')
,(69,'B','Aset')
,(69,'C','Liabilitas')
,(69,'D','Biaya')
,(70,'A','Audit strategy')
,(70,'B','Audit risk')
,(70,'C','Materiality')
,(70,'D','Audit assertion')
;
INSERT INTO multiplechoice_choices (multiplechoice_question_id,choice,label) VALUES 
(71,'A','Audit strategy')
,(71,'B','Audit risk')
,(71,'C','Materiality')
,(71,'D','Audit assertion')
,(72,'A','Completeness')
,(72,'B','Existence')
,(72,'C','Accuracy')
,(72,'D','Calculation')
,(73,'A','Substantive Tests (Procedures)')
,(73,'B','Test of Controls (TOCs)')
;
INSERT INTO multiplechoice_choices (multiplechoice_question_id,choice,label) VALUES 
(73,'C','Vouching')
,(73,'D','Verification')
,(74,'A','Inspeksi ')
,(74,'B','Pengamatan')
,(74,'C','Permintaan keterangan (tanya jawab)')
,(74,'D','Permintaan Konfirmasi')
,(75,'A','Inspeksi')
,(75,'B','Pengamatan')
,(75,'C','Permintaan keterangan (tanya jawab)')
,(75,'D','Permintaan Konfirmasi')
;
INSERT INTO multiplechoice_choices (multiplechoice_question_id,choice,label) VALUES 
(76,'A','Chartered Public Accountant')
,(76,'B','Certification Public Accountant')
,(76,'C','Certified Public Accountant')
,(76,'D','Certify Public Accountant')
,(77,'A','Jasa audit atas informasi keuangan historis')
,(77,'B','Jasa reviu atas informasi keuangan historis')
,(77,'C','Jasa asurans lainnya')
,(77,'D','Jasa konsultasi')
,(78,'A','Jasa audit atas informasi keuangan historis')
,(78,'B','Jasa reviu atas informasi keuangan historis')
;
INSERT INTO multiplechoice_choices (multiplechoice_question_id,choice,label) VALUES 
(78,'C','Jasa asurans lainnya')
,(78,'D','Jasa konsultasi')
,(79,'A','am')
,(79,'B',' is')
,(79,'C','are')
,(79,'D','be')
,(80,'A','constructive')
,(80,'B',' construction')
,(80,'C','construct')
,(80,'D','constructed')
;
INSERT INTO multiplechoice_choices (multiplechoice_question_id,choice,label) VALUES 
(81,'A','on')
,(81,'B','through')
,(81,'C','into')
,(81,'D','without')
,(82,'A','seals')
,(82,'B',' seal')
,(82,'C','sealing')
,(82,'D','sealed')
,(83,'A','calling')
,(83,'B',' will call')
;
INSERT INTO multiplechoice_choices (multiplechoice_question_id,choice,label) VALUES 
(83,'C','call')
,(83,'D','called')
,(84,'A','including')
,(84,'B',' include')
,(84,'C','been included')
,(84,'D','included')
,(85,'A','final')
,(85,'B',' finalize')
,(85,'C','finally')
,(85,'D','finality')
;
INSERT INTO multiplechoice_choices (multiplechoice_question_id,choice,label) VALUES 
(86,'A','more efficient')
,(86,'B','most efficient')
,(86,'C','the most efficient')
,(86,'D','the more efficient')
,(87,'A','which')
,(87,'B',' whose')
,(87,'C','who')
,(87,'D','whom')
,(88,'A','at')
,(88,'B',' from')
;
INSERT INTO multiplechoice_choices (multiplechoice_question_id,choice,label) VALUES 
(88,'C','until')
,(88,'D','on')
,(89,'A','but')
,(89,'B',' and')
,(89,'C','as')
,(89,'D','though')
,(90,'A','aware')
,(90,'B',' await')
,(90,'C','awaken')
,(90,'D','awe')
;
INSERT INTO multiplechoice_choices (multiplechoice_question_id,choice,label) VALUES 
(91,'A','be filing')
,(91,'B',' is filed')
,(91,'C','be filed')
,(91,'D','is filing')
,(92,'A','between')
,(92,'B',' with')
,(92,'C','through')
,(92,'D','from')
,(93,'A','made')
,(93,'B',' has made')
;
INSERT INTO multiplechoice_choices (multiplechoice_question_id,choice,label) VALUES 
(93,'C','make')
,(93,'D','makes')
,(94,'A','fast')
,(94,'B',' fastest')
,(94,'C','the faster')
,(94,'D','faster')
,(95,'A','or')
,(95,'B',' and')
,(95,'C','where')
,(95,'D','during')
;
INSERT INTO multiplechoice_choices (multiplechoice_question_id,choice,label) VALUES 
(96,'A','assist')
,(96,'B',' were assisting')
,(96,'C','assists')
,(96,'D','are assisting')
,(97,'A','to send')
,(97,'B',' sending')
,(97,'C','will send')
,(97,'D','sends')
,(98,'A','smooth')
,(98,'B',' smoothness')
;
INSERT INTO multiplechoice_choices (multiplechoice_question_id,choice,label) VALUES 
(98,'C','smoothed')
,(98,'D','smoothly')
,(99,'A','is list ')
,(99,'B',' listing')
,(99,'C','is listed')
,(99,'D','is listing')
,(100,'A','to work')
,(100,'B',' was working')
,(100,'C','workable')
,(100,'D','worked')
;
INSERT INTO multiplechoice_choices (multiplechoice_question_id,choice,label) VALUES 
(101,'A','are')
,(101,'B',' is')
,(101,'C','being')
,(101,'D','be')
,(102,'A','and')
,(102,'B',' the')
,(102,'C','but')
,(102,'D','nor')
,(103,'A','among')
,(103,'B',' between')
;
INSERT INTO multiplechoice_choices (multiplechoice_question_id,choice,label) VALUES 
(103,'C','from')
,(103,'D','beside')
,(104,'A','soon')
,(104,'B',' as soon')
,(104,'C','as soon as')
,(104,'D','soon than')
,(105,'A','had sold')
,(105,'B',' don’t sell')
,(105,'C','will sell')
,(105,'D','would not sell')
;
INSERT INTO multiplechoice_choices (multiplechoice_question_id,choice,label) VALUES 
(106,'A','explains')
,(106,'B',' is explaining')
,(106,'C','explain')
,(106,'D','explaining')
,(107,'A','Raise')
,(107,'B',' Risen')
,(107,'C','Rising')
,(107,'D','Raised')
,(108,'A','late is always')
,(108,'B',' is always late')
;
INSERT INTO multiplechoice_choices (multiplechoice_question_id,choice,label) VALUES 
(108,'C','always late is')
,(108,'D','is late always')
,(109,'A','Unless')
,(109,'B',' However')
,(109,'C','Since')
,(109,'D','Even though')
,(110,'A','a meeting')
,(110,'B',' an hour')
,(110,'C','an appointment')
,(110,'D','a time')
;
INSERT INTO multiplechoice_choices (multiplechoice_question_id,choice,label) VALUES 
(111,'A','was disappointed')
,(111,'B',' were disappointed')
,(111,'C','was disappointing')
,(111,'D','were disappointing')
,(112,'A','are')
,(112,'B',' is')
,(112,'C','were')
,(112,'D','has')
,(113,'A','with')
,(113,'B',' then')
;
INSERT INTO multiplechoice_choices (multiplechoice_question_id,choice,label) VALUES 
(113,'C','between')
,(113,'D','among')
,(114,'A','During')
,(114,'B',' Because')
,(114,'C','In spite of')
,(114,'D','Although')
,(115,'A','organization')
,(115,'B',' organizing')
,(115,'C','organized')
,(115,'D','organize')
;
INSERT INTO multiplechoice_choices (multiplechoice_question_id,choice,label) VALUES 
(116,'A','are include')
,(116,'B',' have included')
,(116,'C','have included')
,(116,'D','is including')
,(117,'A','hire')
,(117,'B',' hiring')
,(117,'C','hired')
,(117,'D','to hire')
,(118,'A','of')
,(118,'B',' in')
;
INSERT INTO multiplechoice_choices (multiplechoice_question_id,choice,label) VALUES 
(118,'C','for')
,(118,'D','on')
,(119,'A','paid')
,(119,'B',' will pay')
,(119,'C','have paid')
,(119,'D','are paying')
,(120,'A','because')
,(120,'B',' that')
,(120,'C','until')
,(120,'D','when')
;
INSERT INTO multiplechoice_choices (multiplechoice_question_id,choice,label) VALUES 
(121,'A','at')
,(121,'B',' with')
,(121,'C','into')
,(121,'D','for')
,(122,'A','is enclosed')
,(122,'B',' enclose')
,(122,'C','enclosing')
,(122,'D','enclosed')
,(123,'A','advise')
,(123,'B',' adverse')
;
INSERT INTO multiplechoice_choices (multiplechoice_question_id,choice,label) VALUES 
(123,'C','advice')
,(123,'D','adversity')
,(124,'A','in')
,(124,'B',' on')
,(124,'C','over')
,(124,'D','at')
,(125,'A','to ascend')
,(125,'B',' to increase')
,(125,'C','to escalate')
,(125,'D','to rise')
;
INSERT INTO multiplechoice_choices (multiplechoice_question_id,choice,label) VALUES 
(126,'A','effective')
,(126,'B',' effect')
,(126,'C','effectiveness')
,(126,'D','effectively')
,(127,'A','or')
,(127,'B',' since')
,(127,'C','because')
,(127,'D','but')
;
