INSERT INTO exam.gti_questions (nomor,soal,jawaban,quiz_code) VALUES 
(1,'qpdtQPDT','4','gti_pci')
,(1,'John lebih lamban daripada Dani,John lebih cepat daripada Roy,Siapa yang terlamban?;Roy,John,Dani','0','gti_penalaran')
,(1,'KNP','0','gti_jh')
,(1,'6,11,17','2','gti_kka')
,(1,NULL,'1','gti_orientasi')
,(2,'mnfqKNFQ','3','gti_pci')
,(2,'Rani Lebih pendek daripada Susi,Rani lebih tinggi daripada Rita,Siapa yang tertinggi?;Rani,Susi,Rita','1','gti_penalaran')
,(2,'GKN','0','gti_jh')
,(2,'15,1,7','0','gti_kka')
,(2,NULL,'0','gti_orientasi')
;
INSERT INTO exam.gti_questions (nomor,soal,jawaban,quiz_code) VALUES 
(3,'RWMQjwkh','1','gti_pci')
,(3,'Laras lebih cerdas daripada Lina,Laras lebih bodoh daripada Mona,Siapa yang tercerdas? ;Lina,Laras,Mona','2','gti_penalaran')
,(3,'QVY','0','gti_jh')
,(3,'12,19,7','1','gti_kka')
,(3,NULL,'2','gti_orientasi')
,(4,'TBWJnbhm','1','gti_pci')
,(4,'Adam lebih sedih daripada Andi,Ardi lebih sedih daripada Adam,Siapa yang tersedih?;Adam,Ardi,Andi','1','gti_penalaran')
,(4,'DGL','1','gti_jh')
,(4,'20,5,13','1','gti_kka')
,(4,NULL,'2','gti_orientasi')
;
INSERT INTO exam.gti_questions (nomor,soal,jawaban,quiz_code) VALUES 
(5,'bktrPKTN','2','gti_pci')
,(5,'Toni lebih dingin daripada Yudi,Dodi lebih dingin daripada Toni,Siapa yang terdingin?;Yudi,Toni,Dodi','2','gti_penalaran')
,(5,'JLQ','1','gti_jh')
,(5,'13,18,26','2','gti_kka')
,(5,NULL,'2','gti_orientasi')
,(6,'hmtbFQJK','0','gti_pci')
,(6,'Anna lebih pendek daripada Lisa,Lisa lebih pendek daripada Ina,Siapa yang terpendek?;Lisa,Ina,Anna','2','gti_penalaran')
,(6,'JOR','0','gti_jh')
,(6,'2,15,10','0','gti_kka')
,(6,NULL,'0','gti_orientasi')
;
INSERT INTO exam.gti_questions (nomor,soal,jawaban,quiz_code) VALUES 
(7,'kdfgKMHT','1','gti_pci')
,(7,'Dito lebih cerdas daripada Beno,Beno lebih bodoh daripada Adam,Siapa yang terbodoh?;Dito,Beno,Adam','1','gti_penalaran')
,(7,'DFI','1','gti_jh')
,(7,'15,9,20','1','gti_kka')
,(7,NULL,'3','gti_orientasi')
,(8,'JFRTjdbt','2','gti_pci')
,(8,'Lusi lebih lamban daripada Nora,Nora lebih lamban daripada Elsa,Siapa yang tercepat?;Elsa,Lusi,Nora','0','gti_penalaran')
,(8,'JNP','0','gti_jh')
,(8,'12,19,24','0','gti_kka')
,(8,NULL,'3','gti_orientasi')
;
INSERT INTO exam.gti_questions (nomor,soal,jawaban,quiz_code) VALUES 
(9,'MNBPmnbr','3','gti_pci')
,(9,'Olga lebih hangat daripada Ita,Tami lebih hangat daripada Olga,Siapa yang terhangat?;Olga,Tami,Ita','1','gti_penalaran')
,(9,'BDH','1','gti_jh')
,(9,'5,20,12','1','gti_kka')
,(9,NULL,'3','gti_orientasi')
,(10,'MRNDgrqh','1','gti_pci')
,(10,'Sita Lebih tinggi daripada Dian,Lina lebih pendek daripada Dian,Siapa yang terpendek?;Dian,Lina,Sita','1','gti_penalaran')
,(10,'RUW','0','gti_jh')
,(10,'4,11,17','0','gti_kka')
,(10,NULL,'0','gti_orientasi')
;
INSERT INTO exam.gti_questions (nomor,soal,jawaban,quiz_code) VALUES 
(11,'tkjgWKNG','2','gti_pci')
,(11,'Lulu lebih tinggi daripada Tia,Mira lebih pendek daripada Tia,Siapa yang terpendek?;Tia,Mira,Lulu','1','gti_penalaran')
,(11,'MQV','1','gti_jh')
,(11,'29,16,22','0','gti_kka')
,(11,NULL,'1','gti_orientasi')
,(12,'kfhmGJRM','1','gti_pci')
,(12,'Eric lebih gembira daripada Kris,Eric lebih sedih daripada Edi,Siapa yang tersedih?;Kris,Eric,Edi','0','gti_penalaran')
,(12,'MRV','0','gti_jh')
,(12,'28,16,23','1','gti_kka')
,(12,NULL,'1','gti_orientasi')
;
INSERT INTO exam.gti_questions (nomor,soal,jawaban,quiz_code) VALUES 
(13,'RHWPbgkj','0','gti_pci')
,(13,'Anton lebih kuat daripada Toni,Toni lebih kuat daripada Andi,Siapa yang terkuat?;Andi,Anton,Toni','1','gti_penalaran')
,(13,'FKM','0','gti_jh')
,(13,'27,20,15','0','gti_kka')
,(13,NULL,'1','gti_orientasi')
,(14,'bwnjHWTJ','2','gti_pci')
,(14,'David lebih tua daripada Beni,Roy lebih tua daripada David,Siapa yang termuda?;Beni,Roy,David','0','gti_penalaran')
,(14,'NSW','0','gti_jh')
,(14,'15,27,22','0','gti_kka')
,(14,NULL,'0','gti_orientasi')
;
INSERT INTO exam.gti_questions (nomor,soal,jawaban,quiz_code) VALUES 
(15,'wrbdWRJD','3','gti_pci')
,(15,'Tia lebih sedih daripada Ina,Rika lebih gembira daripada Ina,Siapa yang paling gembira?;Rika,Ina,Tia','0','gti_penalaran')
,(15,'EGL','1','gti_jh')
,(15,'22,14,27','1','gti_kka')
,(15,NULL,'3','gti_orientasi')
,(16,'jtkpJTKP','4','gti_pci')
,(16,'Eric lebih lamban daripada Paul,Tio lebih cepat daripada Paul,Siapa yang tercepat?;Tio,Paul,Eric','0','gti_penalaran')
,(16,'SUX','1','gti_jh')
,(16,'29,16,22','0','gti_kka')
,(16,NULL,'1','gti_orientasi')
;
INSERT INTO exam.gti_questions (nomor,soal,jawaban,quiz_code) VALUES 
(17,'RJTHrjkh','3','gti_pci')
,(17,'Rina lebih kuat daripada Rita,Lisa lebih lemah daripada Rita,Siapa yang terlemah?;Rita,Rina,Lisa','2','gti_penalaran')
,(17,'QVX','0','gti_jh')
,(17,'23,29,16','2','gti_kka')
,(17,NULL,'1','gti_orientasi')
,(18,'WPTRwqfg','1','gti_pci')
,(18,'Soni lebih cepat daripada Joni,Joni lebih cepat daripada Paul,Siapa yang tercepat?;Paul,Joni,Soni','2','gti_penalaran')
,(18,'OSX','1','gti_jh')
,(18,'30,24,16','2','gti_kka')
,(18,NULL,'0','gti_orientasi')
;
INSERT INTO exam.gti_questions (nomor,soal,jawaban,quiz_code) VALUES 
(19,'GRJDtrjp','2','gti_pci')
,(19,'Rini lebih gemuk daripada Elsa,Elsa lebih gemuk daripada Lulu,Siapa yang tergemuk?;Rini,Elsa,Lulu','0','gti_penalaran')
,(19,'GKM','0','gti_jh')
,(19,'10,25,18','0','gti_kka')
,(19,NULL,'0','gti_orientasi')
,(20,'JBKDjbkd','4','gti_pci')
,(20,'Rita lebih lemah daripada Ina,Anna lebih kuat daripada Ina ,Siapa yang terkuat?;Anna,Ina,Rita','0','gti_penalaran')
,(20,'KMQ','1','gti_jh')
,(20,'26,18,12','0','gti_kka')
,(20,NULL,'1','gti_orientasi')
;
INSERT INTO exam.gti_questions (nomor,soal,jawaban,quiz_code) VALUES 
(21,'BPMFnpqg','1','gti_pci')
,(21,'Ardi lebih tua daripada Tomi,Robi lebih tua daripada Ardi,Siapa yang tertua?;Robi,Tomi,Ardi','0','gti_penalaran')
,(21,'RUY','1','gti_jh')
,(21,'5,10,18','2','gti_kka')
,(21,NULL,'0','gti_orientasi')
,(22,'HQPWmktf','0','gti_pci')
,(22,'Anto lebih cedas daripada Dito,Anto lebih bodoh daripada Soni,Siapa yang terbodoh?;Anto,Dito,Soni','1','gti_penalaran')
,(22,'RVY','0','gti_jh')
,(22,'17,9,2','0','gti_kka')
,(22,NULL,'3','gti_orientasi')
;
INSERT INTO exam.gti_questions (nomor,soal,jawaban,quiz_code) VALUES 
(23,'PJBMpnbm','3','gti_pci')
,(23,'Yani lebih dingin daripada Olga,Olga lebih dingin daripada Rika,Siapa yang terdingin?;Olga,Yani,Rika','1','gti_penalaran')
,(23,'UXZ','0','gti_jh')
,(23,'3,14,8','1','gti_kka')
,(23,NULL,'1','gti_orientasi')
,(24,'nkpbHRDG','0','gti_pci')
,(24,'Della lebih muda daripada Nadia,Della lebih tua daripada Sita,Siapa yang termuda?;Nadia,Sita,Della','1','gti_penalaran')
,(24,'CHK','0','gti_jh')
,(24,'10,21,16','0','gti_kka')
,(24,NULL,'3','gti_orientasi')
;
INSERT INTO exam.gti_questions (nomor,soal,jawaban,quiz_code) VALUES 
(25,'WPFHwpfh','4','gti_pci')
,(25,'Robby lebih muda daripada Tomi,Tomi lebih muda daripada Soni,Siapa yang tertua?;Robby,Soni,Tomi','1','gti_penalaran')
,(25,'GJO','1','gti_jh')
,(25,'21,16,9','2','gti_kka')
,(25,NULL,'1','gti_orientasi')
,(26,'gqbfKQBF','3','gti_pci')
,(26,'Elsa lebih buruk daripada Susi,Mira lebih baik daripada Susi ,Siapa yang terbaik?;Elsa,Susi,Mira','2','gti_penalaran')
,(26,'NPU','1','gti_jh')
,(26,'23,15,10','0','gti_kka')
,(26,NULL,'3','gti_orientasi')
;
INSERT INTO exam.gti_questions (nomor,soal,jawaban,quiz_code) VALUES 
(27,'pdbgTFKN','0','gti_pci')
,(27,'Adi lebih sedih daripada Tio,Roy lebih sedih daripada Adi,Siapa yang tersedih?;Adi,Tio,Roy','2','gti_penalaran')
,(27,'KNS','1','gti_jh')
,(27,'2,8,15','2','gti_kka')
,(27,NULL,'2','gti_orientasi')
,(28,'gqhjGNHJ','3','gti_pci')
,(28,'Diah lebih cerdas daripada Lisa,Elli lebih cerdas daripada Diah,Siapa yang terbodoh?;Lisa,Elli,Diah','0','gti_penalaran')
,(28,'QTX','1','gti_jh')
,(28,'28,13,21','1','gti_kka')
,(28,NULL,'2','gti_orientasi')
;
INSERT INTO exam.gti_questions (nomor,soal,jawaban,quiz_code) VALUES 
(29,'wtdkWTDP','3','gti_pci')
,(29,'Ina lebih tinggi daripada Dewi,Ina lebih pendek daripada Anna,Siapa yang tertinggi?;Anna,Ina,Dewi','0','gti_penalaran')
,(29,'QUX','0','gti_jh')
,(29,'13,18,5','2','gti_kka')
,(29,NULL,'2','gti_orientasi')
,(30,'DNBPwnbp','3','gti_pci')
,(30,'Erwin lebih muda daripada Edi,Erwin lebih tua daripada Soni,Siapa yang tertua?;Edi,Erwin,Soni','0','gti_penalaran')
,(30,'EJN','0','gti_jh')
,(30,'23,15,29','1','gti_kka')
,(30,NULL,'3','gti_orientasi')
;
INSERT INTO exam.gti_questions (nomor,soal,jawaban,quiz_code) VALUES 
(31,'DPGWdjnr','1','gti_pci')
,(31,'Algi lebih ringan daripada Tono,Tino lebih berat daripada Tono,Siapa yang terberat?;Tino,Algi,Tono','0','gti_penalaran')
,(31,'DHJ','0','gti_jh')
,(31,'15,30,22','1','gti_kka')
,(31,NULL,'2','gti_orientasi')
,(32,'jbqnJBQN','4','gti_pci')
,(32,'Olga lebih kuat daripada Lina,Nora lebih lemah daripada Lina,Siapa yang terkuat?;Lina,Olga,Nora','1','gti_penalaran')
,(32,'QTV','1','gti_jh')
,(32,'20,6,12','0','gti_kka')
,(32,NULL,'1','gti_orientasi')
;
INSERT INTO exam.gti_questions (nomor,soal,jawaban,quiz_code) VALUES 
(33,'GKTBwkmn','1','gti_pci')
,(33,'Tina lebih ringan daripada Tini,Tina lebih berat daripada Susi,Siapa yang terringan?;Susi,Tina,Tini','0','gti_penalaran')
,(33,'NSU','0','gti_jh')
,(33,'18,25,13','1','gti_kka')
,(33,NULL,'1','gti_orientasi')
,(34,'bmgrBFTR','2','gti_pci')
,(34,'Wati lebih muda daripada Dewi,Dian lebih tua daripada Dewi,Siapa yang tertua?;Dewi,Dian,Wati','1','gti_penalaran')
,(34,'GLO','0','gti_jh')
,(34,'15,10,21','2','gti_kka')
,(34,NULL,'3','gti_orientasi')
;
INSERT INTO exam.gti_questions (nomor,soal,jawaban,quiz_code) VALUES 
(35,'TNFGtjfq','2','gti_pci')
,(35,'Adi lebih ramping daripada Bram,Bram lebih ramping daripada Tio,Siapa yang teramping?;Bram,Tio,Adi','2','gti_penalaran')
,(35,'ILP','1','gti_jh')
,(35,'12,23,18','0','gti_kka')
,(35,NULL,'0','gti_orientasi')
,(36,'TRGDtpbd','2','gti_pci')
,(36,'Anna lebih kuat daripada Ani,Anna lebih lemah daripada Ita,Siapa yang terlemah?;Ita,Ani,Anna','1','gti_penalaran')
,(36,'NPS','1','gti_jh')
,(36,'16,29,23','0','gti_kka')
,(36,NULL,'0','gti_orientasi')
;
INSERT INTO exam.gti_questions (nomor,soal,jawaban,quiz_code) VALUES 
(37,'btnwDMQK','0','gti_pci')
,(37,'Dani lebih cerdas daripada Doni,Dani lebih bodoh daripada Adam,Siapa yang tercerdas?;Adam,Dani,Doni','0','gti_penalaran')
,(37,'HLQ','0','gti_jh')
,(37,'11,24,16','1','gti_kka')
,(37,NULL,'2','gti_orientasi')
,(38,'gphfTMHR','1','gti_pci')
,(38,'Didit lebih tinggi daripada Roy,Roy lebih tinggi daripada Roni,Siapa yang terpendek?;Didit,Roy,Roni','2','gti_penalaran')
,(38,'LOQ','0','gti_jh')
,(38,'20,6,12','0','gti_kka')
,(38,NULL,'1','gti_orientasi')
;
INSERT INTO exam.gti_questions (nomor,soal,jawaban,quiz_code) VALUES 
(39,'drqjDRQJ','4','gti_pci')
,(39,'Paul lebih baik daripada Eric,Toni lebih buruk daripada Eric,Siapa yang terbaik?;Eric,Toni,Paul','2','gti_penalaran')
,(39,'QSW','1','gti_jh')
,(39,'18,4,12','1','gti_kka')
,(39,NULL,'3','gti_orientasi')
,(40,'RGQWtjbw','1','gti_pci')
,(40,'Susi lebih dingin daripada Nora,Nora lebih dingin daripada Ita,Siapa yang terdingin?;Ita,Susi,Nora','1','gti_penalaran')
,(40,'NRW','1','gti_jh')
,(40,'13,25,20','0','gti_kka')
,(40,NULL,'2','gti_orientasi')
;
INSERT INTO exam.gti_questions (nomor,soal,jawaban,quiz_code) VALUES 
(41,'mfhbMFHB','4','gti_pci')
,(41,'Bima lebih ringan daripada John,Toni lebih ringan daripada Bima,Siapa yang terberat?;John,Bima,Toni','0','gti_penalaran')
,(41,'RWY','0','gti_jh')
,(41,'21,14,9','0','gti_kka')
,(41,NULL,'1','gti_orientasi')
,(42,'RFNWrfgt','2','gti_pci')
,(42,'Farid lebih hangat daripada Paul,Eric lebih hangat daripada Farid,Siapa yang terhangat?;Paul,Eric,Farid','1','gti_penalaran')
,(42,'OTV','0','gti_jh')
,(42,'27,14,20','0','gti_kka')
,(42,NULL,'3','gti_orientasi')
;
INSERT INTO exam.gti_questions (nomor,soal,jawaban,quiz_code) VALUES 
(43,'PRJQgmnk','0','gti_pci')
,(43,'Lia lebih lemah daripada Tia,Lia lebih kuat daripada Yuli ,Siapa yang terkuat?;Lia,Yuli,Tia','2','gti_penalaran')
,(43,'LOT','1','gti_jh')
,(43,'21,14,6','2','gti_kka')
,(43,NULL,'0','gti_orientasi')
,(44,'wnbkWNBK','4','gti_pci')
,(44,'Andi lebih ringan daripada Tomi,Roy lebih berat daripada Tomi,Siapa yang terberat?;Andi,Tomi,Roy','2','gti_penalaran')
,(44,'GLO','0','gti_jh')
,(44,'18,24,11','2','gti_kka')
,(44,NULL,'3','gti_orientasi')
;
INSERT INTO exam.gti_questions (nomor,soal,jawaban,quiz_code) VALUES 
(45,'drnqPBNK','1','gti_pci')
,(45,'Roni lebih muda daripada Rino,Roy lebih muda daripada Roni,Siapa yang tertua?;Roy,Roni,Rino','2','gti_penalaran')
,(45,'FIM','1','gti_jh')
,(45,'26,11,18','0','gti_kka')
,(45,NULL,'2','gti_orientasi')
,(46,'BRGWfrmw','2','gti_pci')
,(46,'Lulu Lebih cepat daripada Lita,Susi lebih lamban daripada Lita,Siapa yang terlamban?;Lulu,Susi,Lita','1','gti_penalaran')
,(46,'BDG','1','gti_jh')
,(46,'9,1,14','1','gti_kka')
,(46,NULL,'1','gti_orientasi')
;
INSERT INTO exam.gti_questions (nomor,soal,jawaban,quiz_code) VALUES 
(47,'hgbpKRBP','2','gti_pci')
,(47,'Tomi Lebih muda daripada Budi,Budi lebih muda daripada Rio,Siapa yang tertua?;Budi,Rio,Tomi','1','gti_penalaran')
,(47,'NRU','0','gti_jh')
,(47,'16,21,10','2','gti_kka')
,(47,NULL,'2','gti_orientasi')
,(48,'tpmgTPMG','4','gti_pci')
,(48,'Beno Lebih tinggi daripada Budi,Tono lebih tinggi daripada Beno,Siapa yang terpendek?;Beno,Budi,Tono','1','gti_penalaran')
,(48,'FHM','1','gti_jh')
,(48,'16,21,27','2','gti_kka')
,(48,NULL,'2','gti_orientasi')
;
INSERT INTO exam.gti_questions (nomor,soal,jawaban,quiz_code) VALUES 
(49,'TPFBhqnb','1','gti_pci')
,(49,'Anna lebih tinggi daripada Eva,Eva lebih tinggi daripada Tia,Siapa yang tertinggi?;Eva,Tia,Anna','2','gti_penalaran')
,(49,'PUY','0','gti_jh')
,(49,'13,21,27','0','gti_kka')
,(49,NULL,'2','gti_orientasi')
,(50,'QRKPqrkp','4','gti_pci')
,(50,'Tina lebih lamban daripada Nora,Nora lebih lamban daripada Rini,Siapa yang tercepat?;Rini,Nora,Tina','0','gti_penalaran')
,(50,'KMP','1','gti_jh')
,(50,'9,1,14','1','gti_kka')
,(50,NULL,'1','gti_orientasi')
;
INSERT INTO exam.gti_questions (nomor,soal,jawaban,quiz_code) VALUES 
(51,'rnjkRNJQ','3','gti_pci')
,(51,'JNS','1','gti_jh')
,(51,'14,20,27','2','gti_kka')
,(51,NULL,'0','gti_orientasi')
,(52,'QRFHjnpd','0','gti_pci')
,(52,'FIM','1','gti_jh')
,(52,'16,9,4','0','gti_kka')
,(52,NULL,'0','gti_orientasi')
,(53,'DJBFdqbf','3','gti_pci')
,(53,'CHK','0','gti_jh')
;
INSERT INTO exam.gti_questions (nomor,soal,jawaban,quiz_code) VALUES 
(53,'3,9,17','2','gti_kka')
,(53,NULL,'3','gti_orientasi')
,(54,'gwqmGRJP','1','gti_pci')
,(54,'MOS','1','gti_jh')
,(54,'23,18,12','2','gti_kka')
,(54,NULL,'1','gti_orientasi')
,(55,'drbhDRBW','3','gti_pci')
,(55,'HLO','0','gti_jh')
,(55,'19,13,8','0','gti_kka')
,(55,NULL,'1','gti_orientasi')
;
INSERT INTO exam.gti_questions (nomor,soal,jawaban,quiz_code) VALUES 
(56,'FBRTfbrt','4','gti_pci')
,(56,'KOQ','0','gti_jh')
,(56,'25,10,18','1','gti_kka')
,(56,NULL,'1','gti_orientasi')
,(57,'JQGRjqgr','4','gti_pci')
,(57,'RUZ','1','gti_jh')
,(57,'21,13,8','0','gti_kka')
,(57,NULL,'3','gti_orientasi')
,(58,'BQJMbfwm','2','gti_pci')
,(58,'JMO','0','gti_jh')
;
INSERT INTO exam.gti_questions (nomor,soal,jawaban,quiz_code) VALUES 
(58,'24,29,17','2','gti_kka')
,(58,NULL,'3','gti_orientasi')
,(59,'mjbfHKTP','0','gti_pci')
,(59,'JOR','0','gti_jh')
,(59,'2,17,9','1','gti_kka')
,(59,NULL,'0','gti_orientasi')
,(60,'HWGQkmft','0','gti_pci')
,(60,'HKP','1','gti_jh')
,(60,'4,7,11','2','gti_kka')
,(60,NULL,'0','gti_orientasi')
;
INSERT INTO exam.gti_questions (nomor,soal,jawaban,quiz_code) VALUES 
(61,'RTX','1','gti_jh')
,(62,'KNP','1','gti_jh')
,(63,'HMP','0','gti_jh')
,(64,'BFK','1','gti_jh')
,(65,'SWY','0','gti_jh')
,(66,'PRV','1','gti_jh')
,(67,'ADH','1','gti_jh')
,(68,'FJM','0','gti_jh')
,(69,'MRU','0','gti_jh')
,(70,'SUY','1','gti_jh')
;
INSERT INTO exam.gti_questions (nomor,soal,jawaban,quiz_code) VALUES 
(71,'FKO','0','gti_jh')
,(72,'ILP','1','gti_jh')
;
