INSERT INTO ist_group (code, soal) VALUES ('ist_fa1', 'a=group_fa1_a.png,b=group_fa1_b.png,c=group_fa1_c.png,d=group_fa1_d.png,e=group_fa1_e.png');
INSERT INTO ist_group (code, soal) VALUES ('ist_fa2', 'a=group_fa2_a.png,b=group_fa2_b.png,c=group_fa2_c.png,d=group_fa2_d.png,e=group_fa2_e.png');
INSERT INTO ist_group (code, soal) VALUES ('ist_wu1', 'a=group_wu1_a.png,b=group_wu1_b.png,c=group_wu1_c.png,d=group_wu1_d.png,e=group_wu1_e.png');

INSERT INTO ist_questions (quiz_code, nomor, soal, jawaban) VALUES ('ist_zr', '97', '6,9,12,15,18,21,24', '27');
INSERT INTO ist_questions (quiz_code, nomor, soal, jawaban) VALUES ('ist_zr', '98', '15,16,18,19,21,22,24', '25');
INSERT INTO ist_questions (quiz_code, nomor, soal, jawaban) VALUES ('ist_zr', '99', '19,18,22,21,25,24,28', '27');
INSERT INTO ist_questions (quiz_code, nomor, soal, jawaban) VALUES ('ist_zr', '100', '16,12,17,13,18,14,19', '15');
INSERT INTO ist_questions (quiz_code, nomor, soal, jawaban) VALUES ('ist_zr', '101', '2,4,8,10,20,22,44', '46');
INSERT INTO ist_questions (quiz_code, nomor, soal, jawaban) VALUES ('ist_zr', '102', '15,13,16,12,17,11,18', '10');
INSERT INTO ist_questions (quiz_code, nomor, soal, jawaban) VALUES ('ist_zr', '103', '25,22,11,33,30,15,45', '24');
INSERT INTO ist_questions (quiz_code, nomor, soal, jawaban) VALUES ('ist_zr', '104', '49,51,54,27,9,11,14', '7');
INSERT INTO ist_questions (quiz_code, nomor, soal, jawaban) VALUES ('ist_zr', '105', '2,3,1,3,4,2,4', '5');
INSERT INTO ist_questions (quiz_code, nomor, soal, jawaban) VALUES ('ist_zr', '106', '19,17,20,16,21,15,22', '14');
INSERT INTO ist_questions (quiz_code, nomor, soal, jawaban) VALUES ('ist_zr', '107', '94,92,46,44,22,20,10', '8');
INSERT INTO ist_questions (quiz_code, nomor, soal, jawaban) VALUES ('ist_zr', '108', '5,8,9,8,11,12,11', '14');
INSERT INTO ist_questions (quiz_code, nomor, soal, jawaban) VALUES ('ist_zr', '109', '12,15,19,23,28,33,39', '45');
INSERT INTO ist_questions (quiz_code, nomor, soal, jawaban) VALUES ('ist_zr', '110', '7,5,10,7,21,17,68', '36');
INSERT INTO ist_questions (quiz_code, nomor, soal, jawaban) VALUES ('ist_zr', '111', '11,15,18,9,13,16,8', '12');
INSERT INTO ist_questions (quiz_code, nomor, soal, jawaban) VALUES ('ist_zr', '112', '3,8,15,24,35,48,63', '80');
INSERT INTO ist_questions (quiz_code, nomor, soal, jawaban) VALUES ('ist_zr', '113', '4,5,7,4,8,13,7', '14');
INSERT INTO ist_questions (quiz_code, nomor, soal, jawaban) VALUES ('ist_zr', '114', '8,5,15,18,6,3,9', '12');
INSERT INTO ist_questions (quiz_code, nomor, soal, jawaban) VALUES ('ist_zr', '115', '15,6,18,10,30,23,69', '36');
INSERT INTO ist_questions (quiz_code, nomor, soal, jawaban) VALUES ('ist_zr', '116', '5,35,28,4,11,77,70', '10');
INSERT INTO ist_questions (quiz_code, nomor, soal, jawaban, ist_group_code) VALUES ('ist_fa', '117', '117.png', 'a', 'ist_fa1');
INSERT INTO ist_questions (quiz_code, nomor, soal, jawaban, ist_group_code) VALUES ('ist_fa', '118', '118.png', 'c', 'ist_fa1');
INSERT INTO ist_questions (quiz_code, nomor, soal, jawaban, ist_group_code) VALUES ('ist_fa', '119', '119.png', 'b', 'ist_fa1');
INSERT INTO ist_questions (quiz_code, nomor, soal, jawaban, ist_group_code) VALUES ('ist_fa', '120', '120.png', 'a', 'ist_fa1');
INSERT INTO ist_questions (quiz_code, nomor, soal, jawaban, ist_group_code) VALUES ('ist_fa', '121', '121.png', 'd', 'ist_fa1');
INSERT INTO ist_questions (quiz_code, nomor, soal, jawaban, ist_group_code) VALUES ('ist_fa', '122', '122.png', 'b', 'ist_fa1');
INSERT INTO ist_questions (quiz_code, nomor, soal, jawaban, ist_group_code) VALUES ('ist_fa', '123', '123.png', 'c', 'ist_fa1');
INSERT INTO ist_questions (quiz_code, nomor, soal, jawaban, ist_group_code) VALUES ('ist_fa', '124', '124.png', 'e', 'ist_fa1');
INSERT INTO ist_questions (quiz_code, nomor, soal, jawaban, ist_group_code) VALUES ('ist_fa', '125', '125.png', 'e', 'ist_fa1');
INSERT INTO ist_questions (quiz_code, nomor, soal, jawaban, ist_group_code) VALUES ('ist_fa', '126', '126.png', 'd', 'ist_fa1');
INSERT INTO ist_questions (quiz_code, nomor, soal, jawaban, ist_group_code) VALUES ('ist_fa', '127', '127.png', 'e', 'ist_fa1');
INSERT INTO ist_questions (quiz_code, nomor, soal, jawaban, ist_group_code) VALUES ('ist_fa', '128', '128.png', 'b', 'ist_fa1');
INSERT INTO ist_questions (quiz_code, nomor, soal, jawaban, ist_group_code) VALUES ('ist_fa', '129', '129.png', 'd', 'ist_fa2');
INSERT INTO ist_questions (quiz_code, nomor, soal, jawaban, ist_group_code) VALUES ('ist_fa', '130', '130.png', 'c', 'ist_fa2');
INSERT INTO ist_questions (quiz_code, nomor, soal, jawaban, ist_group_code) VALUES ('ist_fa', '131', '131.png', 'b', 'ist_fa2');
INSERT INTO ist_questions (quiz_code, nomor, soal, jawaban, ist_group_code) VALUES ('ist_fa', '132', '132.png', 'a', 'ist_fa2');
INSERT INTO ist_questions (quiz_code, nomor, soal, jawaban, ist_group_code) VALUES ('ist_fa', '133', '133.png', 'b', 'ist_fa2');
INSERT INTO ist_questions (quiz_code, nomor, soal, jawaban, ist_group_code) VALUES ('ist_fa', '134', '134.png', 'd', 'ist_fa2');
INSERT INTO ist_questions (quiz_code, nomor, soal, jawaban, ist_group_code) VALUES ('ist_fa', '135', '135.png', 'c', 'ist_fa2');
INSERT INTO ist_questions (quiz_code, nomor, soal, jawaban, ist_group_code) VALUES ('ist_fa', '136', '136.png', 'c', 'ist_fa2');
INSERT INTO ist_questions (quiz_code, nomor, soal, jawaban, ist_group_code) VALUES ('ist_wu', '137', '137.png', 'a', 'ist_wu1');
INSERT INTO ist_questions (quiz_code, nomor, soal, jawaban, ist_group_code) VALUES ('ist_wu', '138', '138.png', 'c', 'ist_wu1');
INSERT INTO ist_questions (quiz_code, nomor, soal, jawaban, ist_group_code) VALUES ('ist_wu', '139', '139.png', 'd', 'ist_wu1');
INSERT INTO ist_questions (quiz_code, nomor, soal, jawaban, ist_group_code) VALUES ('ist_wu', '140', '140.png', 'e', 'ist_wu1');
INSERT INTO ist_questions (quiz_code, nomor, soal, jawaban, ist_group_code) VALUES ('ist_wu', '141', '141.png', 'a', 'ist_wu1');
INSERT INTO ist_questions (quiz_code, nomor, soal, jawaban, ist_group_code) VALUES ('ist_wu', '142', '142.png', 'c', 'ist_wu1');
INSERT INTO ist_questions (quiz_code, nomor, soal, jawaban, ist_group_code) VALUES ('ist_wu', '143', '143.png', 'd', 'ist_wu1');
INSERT INTO ist_questions (quiz_code, nomor, soal, jawaban, ist_group_code) VALUES ('ist_wu', '144', '144.png', 'c', 'ist_wu1');
INSERT INTO ist_questions (quiz_code, nomor, soal, jawaban, ist_group_code) VALUES ('ist_wu', '145', '145.png', 'e', 'ist_wu1');
INSERT INTO ist_questions (quiz_code, nomor, soal, jawaban, ist_group_code) VALUES ('ist_wu', '146', '146.png', 'a', 'ist_wu1');
INSERT INTO ist_questions (quiz_code, nomor, soal, jawaban, ist_group_code) VALUES ('ist_wu', '147', '147.png', 'b', 'ist_wu1');
INSERT INTO ist_questions (quiz_code, nomor, soal, jawaban, ist_group_code) VALUES ('ist_wu', '148', '148.png', 'd', 'ist_wu1');
INSERT INTO ist_questions (quiz_code, nomor, soal, jawaban, ist_group_code) VALUES ('ist_wu', '149', '149.png', 'e', 'ist_wu1');
INSERT INTO ist_questions (quiz_code, nomor, soal, jawaban, ist_group_code) VALUES ('ist_wu', '150', '150.png', 'b', 'ist_wu1');
INSERT INTO ist_questions (quiz_code, nomor, soal, jawaban, ist_group_code) VALUES ('ist_wu', '151', '151.png', 'd', 'ist_wu1');
INSERT INTO ist_questions (quiz_code, nomor, soal, jawaban, ist_group_code) VALUES ('ist_wu', '152', '152.png', 'b', 'ist_wu1');
INSERT INTO ist_questions (quiz_code, nomor, soal, jawaban, ist_group_code) VALUES ('ist_wu', '153', '153.png', 'a', 'ist_wu1');
INSERT INTO ist_questions (quiz_code, nomor, soal, jawaban, ist_group_code) VALUES ('ist_wu', '154', '154.png', 'e', 'ist_wu1');
INSERT INTO ist_questions (quiz_code, nomor, soal, jawaban, ist_group_code) VALUES ('ist_wu', '155', '155.png', 'b', 'ist_wu1');
INSERT INTO ist_questions (quiz_code, nomor, soal, jawaban, ist_group_code) VALUES ('ist_wu', '156', '156.png', 'c', 'ist_wu1');
