INSERT INTO personal_questions (soal,nomor,trait,reversed_score,quiz_code,is_tutorial) VALUES 
('Saya selalu meminta ijin jika akan menggunakan masukan orang lain untuk menyelesaikan masalah yang saya hadapi',1,'Sin',0,'hexaco',0)
,('Saya merasa tidak perlu meminta maaf ketika saya melakukan kesalahan',2,'Sin',1,'hexaco',0)
,('Saya selalu mengikuti masukan dari rekan kerja saya karena tidak ingin membuat ia kecewa',3,'Sin',0,'hexaco',0)
,('Saya menerima barang atau uang dari supplier/kontraktor karena merasa sungkan dengan teman-teman yang sudah menerima duluan',4,'Fair',1,'hexaco',0)
,('Saya tetap akan mendukung atasan saya yang melakukan pelanggaran aturan dalam bekerja',5,'Fair',1,'hexaco',0)
,('Saya akan mengikuti permintaan rekan kerja untuk menerima imbalan dari pihak ketiga daripada ditinggalkan oleh mereka',6,'Fair',1,'hexaco',0)
,('Saya hanya memakai alat komunikasi yang paling canggih untuk  mendukung saya dalam bekerja',7,'GreedA',1,'hexaco',0)
,('Saya  selalu  membawa laptop terbaru saya di setiap meeting dengan  mitra kerja',8,'GreedA',1,'hexaco',0)
,('Saya selalu menggunakan mobil kantor untuk  semua aktivitas saya baik untuk urusan kantor maupun di luar kantor',9,'GreedA',1,'hexaco',0)
,('Sebagai pegawai, saya telah memahami semua fasilitas yang seharusnya saya terima sesuai dengan jabatan saya.',10,'Modes',0,'hexaco',0)
;
INSERT INTO personal_questions (soal,nomor,trait,reversed_score,quiz_code,is_tutorial) VALUES 
('Selama ini Saya mendapatkan fasilitas kerja sesuai dengan jabatan saya',11,'Modes',0,'hexaco',0)
,('Ketika merasa tidak enak badan saya langsung mengambil jatah cuti karena saya takut penyakitnya semakin parah.',12,'Fear',1,'hexaco',0)
,('Setiap sakit  saya harus memeriksakan ke berbagai dokter spesialis untuk mendapatkan kepastian mengenai penyakit saya.',13,'Fear',1,'hexaco',0)
,('Saya segera memeriksakan diri ke dokter apabila merasa pusing.',14,'Fear',1,'hexaco',0)
,('Saya cemas menghadapi masa depan saya.',15,'Anx',1,'hexaco',0)
,('Perut saya mendadak sakit ketika dipanggil oleh atasan saya.',16,'Anx',1,'hexaco',0)
,('Tuntutan pekerjaan yang baru membuat saya tertekan.',17,'Anx',1,'hexaco',0)
,('Saya lebih nyaman apabila orang lain yang membuat keputusan',18,'Depen',0,'hexaco',0)
,('Setiap kali akan menentukan pilihan saya harus yakin mendapatkan persetujuan dari orang lain',19,'Depen',0,'hexaco',0)
,('Saya merasa cemas  jika harus mengambil inisiatif untuk memulai suatu perubahan',20,'Depen',1,'hexaco',0)
;
INSERT INTO personal_questions (soal,nomor,trait,reversed_score,quiz_code,is_tutorial) VALUES 
('Saya merasa prihatin dengan penderitaan yang dialami oleh oranglain',21,'Senti',1,'hexaco',0)
,('Saya sulit melupakan orang yang berjasa dalam kehidupan saya',22,'Senti',1,'hexaco',0)
,('Saya sulit melupakan peristiwa-peristiwa penting yang mengubah kehidupan saya',23,'Senti',1,'hexaco',0)
,('Saya merasa bahwa orang lain menghargai saya.',24,'SocSelfES',0,'hexaco',0)
,('Teman-teman saya memiliki penilaian yang positif mengenai diri saya.',25,'SocSelfES',0,'hexaco',0)
,('Saya merasa kesulitan untuk dapat membuat lingkungan menyukai saya.',26,'SocSelfES',1,'hexaco',0)
,('Saat rapat saya lebih senang meminta rekan kerja yang lain untuk menyampaikan pendapat saya daripada harus menyampaikan sendiri pendapat saya.',27,'Sbold',0,'hexaco',0)
,('Saya berani membuka topik pembicaraan saat bertemu dengan orang baru.',28,'Sbold',0,'hexaco',0)
,('Dalam tiap kegiatan kantor, saya berani untuk terlebih dahulu mengajak berkenalan orang-orang yang belum saya kenal.',29,'Sbold',0,'hexaco',0)
,('Saya senang melakukan aktivitas sendirian saja.',30,'Soc',1,'hexaco',0)
;
INSERT INTO personal_questions (soal,nomor,trait,reversed_score,quiz_code,is_tutorial) VALUES 
('Saya menikmati kegiatan mengobrol dengan teman-teman di kantor saya.',31,'Soc',0,'hexaco',0)
,('Saya merupakan orang yang ceria.',32,'Live',0,'hexaco',0)
,('Kehadiran saya dapat menghidupkan suasana dalam kelompok.',33,'Live',0,'hexaco',0)
,('Keceriaan merupakan hal yang penting untuk ditunjukkan dalam kelompok.',34,'Live',0,'hexaco',0)
,('Saya mudah memaafkan orang lain',35,'Forg',0,'hexaco',0)
,('Saya tetap berinteraksi dengan orang yang pernah menyakiti hati saya',36,'Forg',0,'hexaco',0)
,('Saya tetap membantu orang yang pernah bersilisih paham dengan saya',37,'Forg',0,'hexaco',0)
,('Saya menerima dengan mudah permintaan maaf dari orang lain',38,'Forg',0,'hexaco',0)
,('Saya senang membantu orang lain',39,'Gent',0,'hexaco',0)
,('Saya senang menolong tanpa pamrih',40,'Gent',0,'hexaco',0)
;
INSERT INTO personal_questions (soal,nomor,trait,reversed_score,quiz_code,is_tutorial) VALUES 
('Saya senang berinteraksi dengan orang banyak',41,'Gent',0,'hexaco',0)
,('Saya mau menang sendiri jika sedang berdiskusi',42,'Flex',0,'hexaco',0)
,('Saya suka memberikan saran demi kemajuan bersama',43,'Flex',0,'hexaco',0)
,('Saya selalu ingin damai dan rukun dengan siapa saja',44,'Flex',0,'hexaco',0)
,('Saya dapat menerima kritik dengan pikiran yang jernih',45,'Pat',0,'hexaco',0)
,('Saya berusaha sabar menghadapi orang yang membuat saya marah',46,'Pat',0,'hexaco',0)
,('Saya orang yang pendiam.',47,'Pat',0,'hexaco',0)
,('Barang-barang di ruang kerja saya tersimpan dengan tertib pada tempatnya',48,'Org',0,'hexaco',0)
,('Ruang kerja yang tidak teratur menyulitkan saya untuk bekerja dengan baik',49,'Org',0,'hexaco',0)
,('Saya selalu ingat dimana berkas pekerjaan saya diletakkan',50,'Org',0,'hexaco',0)
;
INSERT INTO personal_questions (soal,nomor,trait,reversed_score,quiz_code,is_tutorial) VALUES 
('Bekerja lembur menyita waktu pribadi saya yang amat berharga',51,'Dilg',0,'hexaco',0)
,('Menyerahkan laporan melewati batas waktu yang ditetapkan adalah hal yang wajar',52,'Dilg',1,'hexaco',0)
,('Saya merasa terpaksa bila mengerjakan tugas yang berada di luar pengalaman saya',53,'Dilg',1,'hexaco',0)
,('Saya merasa malu bila tidak dapat menyelesaikan tugas yang diberikan kepada saya',54,'Perfect',1,'hexaco',0)
,('Saya tidak mudah puas dengan prestasi kerja yang sudah saya capai',55,'Perfect',0,'hexaco',0)
,('Saya terus menerus memperbaiki hasil kerja saya sampai batas waktu yang ditentukan',56,'Perfect',0,'hexaco',0)
,('Saya menyiapkan fakta dan informasi terlebih dahulu sebelum menegur rekan kerja yang bekerja seenaknya',57,'Pruden',0,'hexaco',0)
,('Pendapat orang lain sangat berharga dalam membantu saya mengambil keputusan',58,'Pruden',0,'hexaco',0)
,('Saya mencari sumber informasi yang otentik ketika menerima adanya informasi baru dari rekan kerja',59,'Pruden',0,'hexaco',0)
,('Saya mengagumi karya seni lukisan yang dibuat oleh para maestro seniman',60,'AA',0,'hexaco',0)
;
INSERT INTO personal_questions (soal,nomor,trait,reversed_score,quiz_code,is_tutorial) VALUES 
('Pada waktu sengang saya manfaatkan untuk mengunjungi pagelaran kesenian drama kolosal',61,'AA',0,'hexaco',0)
,('Saya memasang lukisan bermotif bali untuk memperindah ruang kerja saya',62,'AA',0,'hexaco',0)
,('Saya akan mencari tau pengalaman yang dialami oleh oranglain terkait dengan caranya menyesuaikan diri dengan budaya yang baru',63,'Inq',0,'hexaco',0)
,('Saya antusias mempelajari sejarah dan perkembangan budaya di suatu daerah',64,'Inq',0,'hexaco',0)
,('Saya mencari informasi dari berbagai sumber yang dapat menjelaskan mengenai kejadian tsunami',65,'Inq',0,'hexaco',0)
,('Saya merasa tertantang untuk mencari cara yang  belum pernah dicoba oleh orang lain dalam menyelesaikan masalah',66,'Crea',0,'hexaco',0)
,('Saya senang jika ada oranglain yang meragukan, mempertanyakan  dan ingin menguji ide baru yang saya sampaikan sehingga saya lebih tertantang untuk mengembangkan ide-ide yang lebih inovatif',67,'Crea',0,'hexaco',0)
,('Saya bisa menanggung resiko jika ternyata ide yang saya terapkan tidak bisa menyelesaikan masalah',68,'Crea',0,'hexaco',0)
,('saya lebih bersemangat menerapkan cara baru untuk menyelesaikan masalah',69,'Uncon',0,'hexaco',0)
,('Saya bisa menerima sudut pandang yang berbeda-beda dalam  menyelesaikan masalah ataupun mencapai target kerja',70,'Uncon',0,'hexaco',0)
;
INSERT INTO personal_questions (soal,nomor,trait,reversed_score,quiz_code,is_tutorial) VALUES 
('Saya membutuhkan waktu yang cukup lama untuk membaca suatu kontrak kerja secara berulang ulang sebelum menandatanganinya',71,'Uncon',0,'hexaco',0)
,('Saya menikmati saat-saat kebersamaan bersama teman',72,'Soc',0,'hexaco',0)
,('Saya tidak khawatir mengenai hal hal yang berada di luar batas kemampuan yang saya miliki',1,'EC',0,'cti',0)
,('Saya lebih suka bertindak daripada sekedar berfikir atau mengeluhkan suatu keadaan',2,'BC',0,'cti',0)
,('Saya merasa jika orang memperlakukan yang buruk terhado diri saya, maka saya harus berfbuat sebaliknya yakni berbuat baik kepada orang tersebut',3,'CT',1,'cti',0)
,('Saya menyadari memperbincangkan tentang keberhasilan-keberhasilan akan mendekatkan pada hasil yang akan dicapai',4,'PST',1,'cti',0)
,('Jika saya menyelesaikan ujian atau tugas penting dengan baik, saya akan membanggakan hasilnya',5,'ET',1,'cti',0)
,('Saya pecaya dengan astrologi dan ramalan bintang atau zodiak',6,'NO',1,'cti',0)
,('Saya tidak mempemasalahkan dan memperdulikan hal hal yang kecil',7,'EC',0,'cti',0)
,('Jika saya terpaksa melalkukan sesuatu tindakan yang tidak menyenangkan, saya akan memandang dari sisi positif dan hal hal yang baiknya bagi diri saya',8,'BC',0,'cti',0)
;
INSERT INTO personal_questions (soal,nomor,trait,reversed_score,quiz_code,is_tutorial) VALUES 
('Pada dasarnya manusia hanya terdapat dua tipe manusia, yang baik dan yang jahat ',9,'CT',1,'cti',0)
,('Saya percaya jika sesuatu yang baik terjadi pada diri saya, maka terjadi juga hal buruk sebagai penyeimbangya',10,'PST',1,'cti',0)
,('Saya percaya semua orang dapat mencapai yang mereka inginkan asalkan mereka punya niat dan tekad yang kuat',11,'ET',1,'cti',0)
,('Saya memimiliki paling satu atau dua benda atau kalimat yang membawa keberuntungan bagi diri saya',12,'NO',1,'cti',0)
,('Saya tidak harus mencapai prestasi yang istimewa untuk menjadi orang yang dihargai',13,'EC',0,'cti',0)
,('Saya berpendapat bahwa tantangan bukanlah sesuatu yang ditakuti akan tetapi untuk menguji kemampuan diri sendiri dan belajar lebih lanjut',14,'BC',0,'cti',0)
,('Saya merasa bahwa pada kenyataanya terdapat banyak jalan sayang salah untuk melakukan sesuatu dan hanya tersedia satu jalan yang benar',15,'CT',1,'cti',0)
,('Saya percaya adanya pertanda buruk dan pertanda baik dari suatu kejadian yang akan dialami oleh seseorang',16,'PST',1,'cti',0)
,('Saya berpendapat bahwa setiap orang mencintai orang tuanya',17,'ET',1,'cti',0)
,('Saya percaya pada adanya keberadaan hantu dan yang sejenisnya',18,'NO',1,'cti',0)
;
INSERT INTO personal_questions (soal,nomor,trait,reversed_score,quiz_code,is_tutorial) VALUES 
('Saya lebih cenderung hal-hal yang menyenangkan daripada kejaian buruk yang telah saya alami di masa yang telah lalu',19,'EC',0,'cti',0)
,('Jika saya dihadpkan pada tugas yang sulit maka saya cenderung menyemangati diri saya sendiri agar dapat menyelesaikannya',20,'BC',0,'cti',0)
,('Saya cenderung mengelompokkan orang sebagai orang -orang medukung dan sepaham dengan saya dan orang-orang yang berlawanan dan bertenatngan dengan saya',21,'CT',1,'cti',0)
,('Saya terjadang berfikir bahwa jika saya terlalu keras menginginkan sesuatu maka akan membuatnya tidak menjadi kenyataan',22,'ET',1,'cti',0)
,('Jika saya berhasil melewati tahap proses wawancara untuk mendapat suatu pekerjaan disebuah perusahaan maka saya akan merasa sangat senang dan saya berfikir akan bisa mendpatkan pekerjaan selalu  ',23,'PST',1,'cti',0)
,('Saya percaya bahwa ada beberapa orang tertentu yang neniliki kemampuan untuk membaca pikiran orang lain',24,'NO',1,'cti',0)
,('Saya tidak pernah menganggap masalah yang dihadapi sebagai persoalan pribadi',25,'EC',0,'cti',0)
,('Ketika saya memperkirakan bahwa akan mengalami kejadian yang tidak menyenangkan, saya akan berhati-hati dalam menghadapinya',26,'BC',0,'cti',0)
,('Saya selalu menilai dan melakukan evaluasi atas apa yang dilakukan oleh orang lain',27,'CT',1,'cti',0)
,('Saya belajar untuk tidak berharap terlalu banyak mengenai kesuksesan  sebab seringkali harapan saya kandas dan tidak terwujud',28,'PST',1,'cti',0)
;
INSERT INTO personal_questions (soal,nomor,trait,reversed_score,quiz_code,is_tutorial) VALUES 
('Saya percaya jika saya berbuat baik maka saya akan mendapat kebaikan di kemudian hari',29,'ET',1,'cti',0)
,('Saya percaya bahwasanya ada beberapa orang yang dapat meramalkan dan melihat mengenai masa depan',30,'NO',1,'cti',0)
,('Adalah wajar untuk menelusuri informasi yang dapat saya gunakan untuk berhadapan orang nantinya',1,'M',0,'d3ad',0)
,('Banyak aktifitas kelompok yang nampaknya membosankan tanpa kehadiran saya',1,'N',0,'d3ad',0)
,('Saya harus menunggu waktu yang tepat untuk mendapatkan kembali para pengikut saya',2,'M',0,'d3ad',0)
,('Saya memaksa untuk mendapatkan rasa hormat yang seharusnya saya terima',2,'N',0,'d3ad',0)
,('Saya menggunakan cara dan taktik yang cerdas untuk mendapatkan apa yang saya inginkan',3,'M',0,'d3ad',0)
,('Saya senang jika saya dikenal oleh orang-orang penting',3,'N',0,'d3ad',0)
,('Saya meyakini rencana yang miliki menguntungkan bagi diri saya, bukan org lain',4,'M',0,'d3ad',0)
,('Saya tahu bahwa saya spesial karena setiap orang mengatakannya kepada saya',4,'N',0,'d3ad',0)
;
INSERT INTO personal_questions (soal,nomor,trait,reversed_score,quiz_code,is_tutorial) VALUES 
('Kebanyakan orang bisa dimanipulasi untuk kepentingan saya',5,'M',0,'d3ad',0)
,('Saya senang jika kebaikan saya dibandingkan dengan orang-orang terkenal',5,'N',0,'d3ad',0)
,('Banyak aktifitas kelompok yang nampaknya membosankan tanpa kehadiran saya',6,'N',0,'d3ad',0)
,('Saya akan mengatakan apapun untuk mendapatkan apa yang saya inginkan',6,'P',0,'d3ad',0)
,('Saya memaksa untuk mendapatkan rasa hormat yang seharusnya saya terima',7,'N',0,'d3ad',0)
,('Mereka yang pernah memiliki masalah dengan saya akan menyesal dikemudian hari',7,'P',0,'d3ad',0)
,('Saya senang jika saya dikenal oleh orang-orang penting',8,'N',0,'d3ad',0)
,('Saya senang mendapatkan  perhatian dari para penguasa atau orang terkenal',8,'P',0,'d3ad',0)
,('Saya tahu bahwa saya spesial karena setiap orang mengatakannya kepada saya',9,'N',0,'d3ad',0)
,('Pembalasan yang diberikan harus perlu cepat dilaksanakan dengan bobot yang setimpal',9,'P',0,'d3ad',0)
;
INSERT INTO personal_questions (soal,nomor,trait,reversed_score,quiz_code,is_tutorial) VALUES 
('Saya senang jika kebaikan saya dibandingkan dengan orang-orang terkenal',10,'N',0,'d3ad',0)
,('Dalam Keadaan tertentu saya bisa berbuat jahat kepada orang lain',10,'P',0,'d3ad',0)
,('Adalah wajar untuk menelusuri informasi yang dapat saya gunakan untuk berhadapan orang nantinya',11,'M',0,'d3ad',0)
,('Saya akan mengatakan apapun untuk mendapatkan apa yang saya inginkan',11,'P',0,'d3ad',0)
,('Saya harus menunggu waktu yang tepat untuk mendapatkan kembali para pengikut saya',12,'M',0,'d3ad',0)
,('Mereka yang pernah memiliki masalah dengan saya akan menyesal dikemudian hari',12,'P',0,'d3ad',0)
,('Saya menggunakan cara dan taktik yang cerdas untuk mendapatkan apa yang saya inginkan',13,'M',0,'d3ad',0)
,('Saya senang mendapatkan  perhatian dari para penguasa atau orang terkenal',13,'P',0,'d3ad',0)
,('Saya meyakini rencana yang miliki menguntungkan bagi diri saya, bukan org lain',14,'M',0,'d3ad',0)
,('Pembalasan yang diberikan harus perlu cepat dilaksanakan dengan bobot yang setimpal',14,'P',0,'d3ad',0)
;
INSERT INTO personal_questions (soal,nomor,trait,reversed_score,quiz_code,is_tutorial) VALUES 
('Kebanyakan orang bisa dimanipulasi untuk kepentingan saya',15,'M',0,'d3ad',0)
,('Dalam Keadaan tertentu saya bisa berbuat jahat kepada orang lain',15,'P',0,'d3ad',0)
,('Saya senang jika kebaikan saya dibandingkan dengan orang-orang terkenal',16,'N',0,'d3ad',0)
,('Kebanyakan orang bisa dimanipulasi untuk kepentingan saya',16,'M',0,'d3ad',0)
,('Saya tahu bahwa saya spesial karena setiap orang mengatakannya kepada saya',17,'N',0,'d3ad',0)
,('Saya meyakini rencana yang miliki menguntungkan bagi diri saya, bukan org lain',17,'M',0,'d3ad',0)
,('Saya senang jika saya dikenal oleh orang-orang penting',18,'N',0,'d3ad',0)
,('Saya menggunakan cara dan taktik yang cerdas untuk mendapatkan apa yang saya inginkan',18,'M',0,'d3ad',0)
,('Saya memaksa untuk mendapatkan rasa hormat yang seharusnya saya terima',19,'N',0,'d3ad',0)
,('Saya harus menunggu waktu yang tepat untuk mendapatkan kembali para pengikut saya',19,'M',0,'d3ad',0)
;
INSERT INTO personal_questions (soal,nomor,trait,reversed_score,quiz_code,is_tutorial) VALUES 
('Banyak aktifitas kelompok yang nampaknya membosankan tanpa kehadiran saya',20,'N',0,'d3ad',0)
,('Adalah wajar untuk menelusuri informasi yang dapat saya gunakan untuk berhadapan orang nantinya',20,'M',0,'d3ad',0)
,('Dalam Keadaan tertentu saya bisa berbuat jahat kepada orang lain',21,'P',0,'d3ad',0)
,('Saya senang jika kebaikan saya dibandingkan dengan orang-orang terkenal',21,'N',0,'d3ad',0)
,('Pembalasan yang diberikan harus perlu cepat dilaksanakan dengan bobot yang setimpal',22,'P',0,'d3ad',0)
,('Saya tahu bahwa saya spesial karena setiap orang mengatakannya kepada saya',22,'N',0,'d3ad',0)
,('Saya senang mendapatkan  perhatian dari para penguasa atau orang terkenal',23,'P',0,'d3ad',0)
,('Saya senang jika saya dikenal oleh orang-orang penting',23,'N',0,'d3ad',0)
,('Mereka yang pernah memiliki masalah dengan saya akan menyesal dikemudian hari',24,'P',0,'d3ad',0)
,('Saya memaksa untuk mendapatkan rasa hormat yang seharusnya saya terima',24,'N',0,'d3ad',0)
;
INSERT INTO personal_questions (soal,nomor,trait,reversed_score,quiz_code,is_tutorial) VALUES 
('Saya akan mengatakan apapun untuk mendapatkan apa yang saya inginkan',25,'P',0,'d3ad',0)
,('Banyak aktifitas kelompok yang nampaknya membosankan tanpa kehadiran saya',25,'N',0,'d3ad',0)
,('Dalam Keadaan tertentu saya bisa berbuat jahat kepada orang lain',26,'P',0,'d3ad',0)
,('Kebanyakan orang bisa dimanipulasi untuk kepentingan saya',26,'M',0,'d3ad',0)
,('Pembalasan yang diberikan harus perlu cepat dilaksanakan dengan bobot yang setimpal',27,'P',0,'d3ad',0)
,('Saya meyakini rencana yang miliki menguntungkan bagi diri saya, bukan org lain',27,'M',0,'d3ad',0)
,('Saya senang mendapatkan  perhatian dari para penguasa atau orang terkenal',28,'P',0,'d3ad',0)
,('Saya menggunakan cara dan taktik yang cerdas untuk mendapatkan apa yang saya inginkan',28,'M',0,'d3ad',0)
,('Mereka yang pernah memiliki masalah dengan saya akan menyesal dikemudian hari',29,'P',0,'d3ad',0)
,('Saya harus menunggu waktu yang tepat untuk mendapatkan kembali para pengikut saya',29,'M',0,'d3ad',0)
;
INSERT INTO personal_questions (soal,nomor,trait,reversed_score,quiz_code,is_tutorial) VALUES 
('Saya akan mengatakan apapun untuk mendapatkan apa yang saya inginkan',30,'P',0,'d3ad',0)
,('Adalah wajar untuk menelusuri informasi yang dapat saya gunakan untuk berhadapan orang nantinya',30,'M',0,'d3ad',0)
;