UPDATE gti_questions SET jawaban=6 WHERE quiz_code = 'gti_kotak' AND nomor = 1; /* 6_291dd475.png */
UPDATE gti_questions SET jawaban=6 WHERE quiz_code = 'gti_kotak' AND nomor = 10; /* 6_8fbf78de.png */
UPDATE gti_questions SET jawaban=5 WHERE quiz_code = 'gti_kotak' AND nomor = 11; /* 5_cab6b766.png */
UPDATE gti_questions SET jawaban=1 WHERE quiz_code = 'gti_kotak' AND nomor = 13; /* 1_aec5bc0f.png */
UPDATE gti_questions SET jawaban=6 WHERE quiz_code = 'gti_kotak' AND nomor = 14; /* 6_7cd9c7ac.png */
UPDATE gti_questions SET jawaban=5 WHERE quiz_code = 'gti_kotak' AND nomor = 15; /* 5_d9ae0ba9.png */
UPDATE gti_questions SET jawaban=8 WHERE quiz_code = 'gti_kotak' AND nomor = 16; /* 8_deb95082.png */
UPDATE gti_questions SET jawaban=2 WHERE quiz_code = 'gti_kotak' AND nomor = 17; /* 2_eed4111e.png */
UPDATE gti_questions SET jawaban=7 WHERE quiz_code = 'gti_kotak' AND nomor = 18; /* 7_df6d12ad.png */
UPDATE gti_questions SET jawaban=3 WHERE quiz_code = 'gti_kotak' AND nomor = 19; /* 3_a9b7fa3c.png */
UPDATE gti_questions SET jawaban=1 WHERE quiz_code = 'gti_kotak' AND nomor = 2; /* 1_f9c34064.png */
UPDATE gti_questions SET jawaban=4 WHERE quiz_code = 'gti_kotak' AND nomor = 20; /* 4_994e01af.png */
UPDATE gti_questions SET jawaban=8 WHERE quiz_code = 'gti_kotak' AND nomor = 21; /* 8_e1a8ac2b.png */
UPDATE gti_questions SET jawaban=4 WHERE quiz_code = 'gti_kotak' AND nomor = 22; /* 4_1f761da9.png */
UPDATE gti_questions SET jawaban=5 WHERE quiz_code = 'gti_kotak' AND nomor = 23; /* 5_74fe8056.png */
UPDATE gti_questions SET jawaban=4 WHERE quiz_code = 'gti_kotak' AND nomor = 24; /* 4_e2fe62dd.png */
UPDATE gti_questions SET jawaban=5 WHERE quiz_code = 'gti_kotak' AND nomor = 25; /* 5_17cb9bc0.png */
UPDATE gti_questions SET jawaban=6 WHERE quiz_code = 'gti_kotak' AND nomor = 26; /* 6_59f8433d.png */
UPDATE gti_questions SET jawaban=6 WHERE quiz_code = 'gti_kotak' AND nomor = 27; /* 6_16e318d2.png */
UPDATE gti_questions SET jawaban=2 WHERE quiz_code = 'gti_kotak' AND nomor = 28; /* 2_e5d604c0.png */
UPDATE gti_questions SET jawaban=3 WHERE quiz_code = 'gti_kotak' AND nomor = 29; /* 3_448a5c70.png */
UPDATE gti_questions SET jawaban=4 WHERE quiz_code = 'gti_kotak' AND nomor = 3; /* 4_046bf0a7.png */
UPDATE gti_questions SET jawaban=4 WHERE quiz_code = 'gti_kotak' AND nomor = 30; /* 4_3b92d67e.png */
UPDATE gti_questions SET jawaban=8 WHERE quiz_code = 'gti_kotak' AND nomor = 31; /* 8_5c8b64db.png */
UPDATE gti_questions SET jawaban=5 WHERE quiz_code = 'gti_kotak' AND nomor = 32; /* 5_b397be80.png */
UPDATE gti_questions SET jawaban=6 WHERE quiz_code = 'gti_kotak' AND nomor = 4; /* 6_ff7cfe90.png */
UPDATE gti_questions SET jawaban=3 WHERE quiz_code = 'gti_kotak' AND nomor = 5; /* 3_23d46ecc.png */
UPDATE gti_questions SET jawaban=1 WHERE quiz_code = 'gti_kotak' AND nomor = 6; /* 1_acdd163a.png */
UPDATE gti_questions SET jawaban=7 WHERE quiz_code = 'gti_kotak' AND nomor = 7; /* 7_292adf48.png */
UPDATE gti_questions SET jawaban=8 WHERE quiz_code = 'gti_kotak' AND nomor = 8; /* 8_6ae58576.png */
UPDATE gti_questions SET jawaban=4 WHERE quiz_code = 'gti_kotak' AND nomor = 9; /* 4_210e7932.png */
