UPDATE personal_questions SET soal = 'Adalah wajar untuk menelusuri informasi yang dapat saya gunakan untuk berhadapan dengan orang nantinya' WHERE trait = 'M' AND nomor = '1' AND quiz_code = 'P2';
UPDATE personal_questions SET soal = 'Banyak aktivitas kelompok yang nampaknya membosankan tanpa kehadiran saya' WHERE trait = 'N' AND nomor = '1' AND quiz_code = 'P2';
UPDATE personal_questions SET soal = 'Saya harus menunggu waktu yang tepat untuk menjalin hubungan kembali dengan orang di sekitar saya' WHERE trait = 'M' AND nomor = '2' AND quiz_code = 'P2';
UPDATE personal_questions SET soal = 'Saya yakin rencana yang saya miliki menguntungkan bagi diri saya, bukan orang lain' WHERE trait = 'M' AND nomor = '4' AND quiz_code = 'P2';
UPDATE personal_questions SET soal = 'Kebanyakan orang bisa dimanfaatkan untuk kepentingan saya' WHERE trait = 'M' AND nomor = '5' AND quiz_code = 'P2';
UPDATE personal_questions SET soal = 'Banyak aktivitas kelompok yang nampaknya membosankan tanpa kehadiran saya' WHERE trait = 'N' AND nomor = '6' AND quiz_code = 'P2';
UPDATE personal_questions SET soal = 'Saya senang mendapatkan perhatian dari orang penting atau orang terkenal' WHERE trait = 'P' AND nomor = '8' AND quiz_code = 'P2';
UPDATE personal_questions SET soal = 'Pembalasan yang diberikan harus dan perlu cepat dilaksanakan dengan bobot yang setimpal' WHERE trait = 'P' AND nomor = '9' AND quiz_code = 'P2';
UPDATE personal_questions SET soal = 'Adalah wajar untuk menelusuri informasi yang dapat saya gunakan untuk berhadapan dengan orang nantinya' WHERE trait = 'M' AND nomor = '11' AND quiz_code = 'P2';
UPDATE personal_questions SET soal = 'Saya harus menunggu waktu yang tepat untuk menjalin hubungan kembali dengan orang di sekitar saya' WHERE trait = 'M' AND nomor = '12' AND quiz_code = 'P2';
UPDATE personal_questions SET soal = 'Saya senang mendapatkan perhatian dari orang penting atau orang terkenal' WHERE trait = 'P' AND nomor = '13' AND quiz_code = 'P2';
UPDATE personal_questions SET soal = 'Saya yakin rencana yang saya miliki menguntungkan bagi diri saya, bukan orang lain' WHERE trait = 'M' AND nomor = '14' AND quiz_code = 'P2';
UPDATE personal_questions SET soal = 'Pembalasan yang diberikan harus dan perlu cepat dilaksanakan dengan bobot yang setimpal' WHERE trait = 'P' AND nomor = '14' AND quiz_code = 'P2';
UPDATE personal_questions SET soal = 'Kebanyakan orang bisa dimanfaatkan untuk kepentingan saya' WHERE trait = 'M' AND nomor = '15' AND quiz_code = 'P2';
UPDATE personal_questions SET soal = 'Kebanyakan orang bisa dimanfaatkan untuk kepentingan saya' WHERE trait = 'M' AND nomor = '16' AND quiz_code = 'P2';
UPDATE personal_questions SET soal = 'Saya yakin rencana yang saya miliki menguntungkan bagi diri saya, bukan orang lain' WHERE trait = 'M' AND nomor = '17' AND quiz_code = 'P2';
UPDATE personal_questions SET soal = 'Saya harus menunggu waktu yang tepat untuk menjalin hubungan kembali dengan orang di sekitar saya' WHERE trait = 'M' AND nomor = '19' AND quiz_code = 'P2';
UPDATE personal_questions SET soal = 'Banyak aktivitas kelompok yang nampaknya membosankan tanpa kehadiran saya' WHERE trait = 'N' AND nomor = '20' AND quiz_code = 'P2';
UPDATE personal_questions SET soal = 'Adalah wajar untuk menelusuri informasi yang dapat saya gunakan untuk berhadapan dengan orang nantinya' WHERE trait = 'M' AND nomor = '20' AND quiz_code = 'P2';
UPDATE personal_questions SET soal = 'Pembalasan yang diberikan harus dan perlu cepat dilaksanakan dengan bobot yang setimpal' WHERE trait = 'P' AND nomor = '22' AND quiz_code = 'P2';
UPDATE personal_questions SET soal = 'Saya senang mendapatkan perhatian dari orang penting atau orang terkenal' WHERE trait = 'P' AND nomor = '23' AND quiz_code = 'P2';
UPDATE personal_questions SET soal = 'Banyak aktivitas kelompok yang nampaknya membosankan tanpa kehadiran saya' WHERE trait = 'N' AND nomor = '25' AND quiz_code = 'P2';
UPDATE personal_questions SET soal = 'Kebanyakan orang bisa dimanfaatkan untuk kepentingan saya' WHERE trait = 'M' AND nomor = '26' AND quiz_code = 'P2';
UPDATE personal_questions SET soal = 'Pembalasan yang diberikan harus dan perlu cepat dilaksanakan dengan bobot yang setimpal' WHERE trait = 'P' AND nomor = '27' AND quiz_code = 'P2';
UPDATE personal_questions SET soal = 'Saya yakin rencana yang saya miliki menguntungkan bagi diri saya, bukan orang lain' WHERE trait = 'M' AND nomor = '27' AND quiz_code = 'P2';
UPDATE personal_questions SET soal = 'Saya senang mendapatkan perhatian dari orang penting atau orang terkenal' WHERE trait = 'P' AND nomor = '28' AND quiz_code = 'P2';
UPDATE personal_questions SET soal = 'Saya harus menunggu waktu yang tepat untuk menjalin hubungan kembali dengan orang di sekitar saya' WHERE trait = 'M' AND nomor = '29' AND quiz_code = 'P2';
UPDATE personal_questions SET soal = 'Adalah wajar untuk menelusuri informasi yang dapat saya gunakan untuk berhadapan dengan orang nantinya' WHERE trait = 'M' AND nomor = '30' AND quiz_code = 'P2';
