INSERT INTO personal_questions (soal, nomor, trait, reversed_score, quiz_code) VALUES ('Adalah wajar untuk menelusuri informasi yang dapat saya gunakan untuk berhadapan orang nantinya', 1, 'M', 0, 'd3ad');
INSERT INTO personal_questions (soal, nomor, trait, reversed_score, quiz_code) VALUES ('Banyak aktifitas kelompok yang nampaknya membosankan tanpa kehadiran saya', 1, 'N', 0, 'd3ad');
INSERT INTO personal_questions (soal, nomor, trait, reversed_score, quiz_code) VALUES ('Saya harus menunggu waktu yang tepat untuk mendapatkan kembali para pengikut saya', 2, 'M', 0, 'd3ad');
INSERT INTO personal_questions (soal, nomor, trait, reversed_score, quiz_code) VALUES ('Saya memaksa untuk mendapatkan rasa hormat yang seharusnya saya terima', 2, 'N', 0, 'd3ad');
INSERT INTO personal_questions (soal, nomor, trait, reversed_score, quiz_code) VALUES ('Saya menggunakan cara dan taktik yang cerdas untuk mendapatkan apa yang saya inginkan', 3, 'M', 0, 'd3ad');
INSERT INTO personal_questions (soal, nomor, trait, reversed_score, quiz_code) VALUES ('Saya senang jika saya dikenal oleh orang-orang penting', 3, 'N', 0, 'd3ad');
INSERT INTO personal_questions (soal, nomor, trait, reversed_score, quiz_code) VALUES ('Saya meyakini rencana yang miliki menguntungkan bagi diri saya, bukan orang lain', 4, 'M', 0, 'd3ad');
INSERT INTO personal_questions (soal, nomor, trait, reversed_score, quiz_code) VALUES ('Saya tahu bahwa saya spesial karena setiap orang mengatakannya kepada saya', 4, 'N', 0, 'd3ad');
INSERT INTO personal_questions (soal, nomor, trait, reversed_score, quiz_code) VALUES ('Kebanyakan orang bisa dimanipulasi untuk kepentingan saya', 5, 'M', 0, 'd3ad');
INSERT INTO personal_questions (soal, nomor, trait, reversed_score, quiz_code) VALUES ('Saya senang jika kebaikan saya dibandingkan dengan orang-orang terkenal', 5, 'N', 0, 'd3ad');
INSERT INTO personal_questions (soal, nomor, trait, reversed_score, quiz_code) VALUES ('Banyak aktifitas kelompok yang nampaknya membosankan tanpa kehadiran saya', 6, 'N', 0, 'd3ad');
INSERT INTO personal_questions (soal, nomor, trait, reversed_score, quiz_code) VALUES ('Saya akan mengatakan apapun untuk mendapatkan apa yang saya inginkan', 6, 'P', 0, 'd3ad');
INSERT INTO personal_questions (soal, nomor, trait, reversed_score, quiz_code) VALUES ('Saya memaksa untuk mendapatkan rasa hormat yang seharusnya saya terima', 7, 'N', 0, 'd3ad');
INSERT INTO personal_questions (soal, nomor, trait, reversed_score, quiz_code) VALUES ('Mereka yang pernah memiliki masalah dengan saya akan menyesal dikemudian hari', 7, 'P', 0, 'd3ad');
INSERT INTO personal_questions (soal, nomor, trait, reversed_score, quiz_code) VALUES ('Saya senang jika saya dikenal oleh orang-orang penting', 8, 'N', 0, 'd3ad');
INSERT INTO personal_questions (soal, nomor, trait, reversed_score, quiz_code) VALUES ('Saya senang mendapatkan  perhatian dari para penguasa atau orang terkenal', 8, 'P', 0, 'd3ad');
INSERT INTO personal_questions (soal, nomor, trait, reversed_score, quiz_code) VALUES ('Saya tahu bahwa saya spesial karena setiap orang mengatakannya kepada saya', 9, 'N', 0, 'd3ad');
INSERT INTO personal_questions (soal, nomor, trait, reversed_score, quiz_code) VALUES ('Pembalasan yang diberikan harus perlu cepat dilaksanakan dengan bobot yang setimpal', 9, 'P', 0, 'd3ad');
INSERT INTO personal_questions (soal, nomor, trait, reversed_score, quiz_code) VALUES ('Saya senang jika kebaikan saya dibandingkan dengan orang-orang terkenal', 10, 'N', 0, 'd3ad');
INSERT INTO personal_questions (soal, nomor, trait, reversed_score, quiz_code) VALUES ('Dalam keadaan tertentu saya bisa berbuat jahat kepada orang lain', 10, 'P', 0, 'd3ad');
INSERT INTO personal_questions (soal, nomor, trait, reversed_score, quiz_code) VALUES ('Adalah wajar untuk menelusuri informasi yang dapat saya gunakan untuk berhadapan orang nantinya', 11, 'M', 0, 'd3ad');
INSERT INTO personal_questions (soal, nomor, trait, reversed_score, quiz_code) VALUES ('Saya akan mengatakan apapun untuk mendapatkan apa yang saya inginkan', 11, 'P', 0, 'd3ad');
INSERT INTO personal_questions (soal, nomor, trait, reversed_score, quiz_code) VALUES ('Saya harus menunggu waktu yang tepat untuk mendapatkan kembali para pengikut saya', 12, 'M', 0, 'd3ad');
INSERT INTO personal_questions (soal, nomor, trait, reversed_score, quiz_code) VALUES ('Mereka yang pernah memiliki masalah dengan saya akan menyesal dikemudian hari', 12, 'P', 0, 'd3ad');
INSERT INTO personal_questions (soal, nomor, trait, reversed_score, quiz_code) VALUES ('Saya menggunakan cara dan taktik yang cerdas untuk mendapatkan apa yang saya inginkan', 13, 'M', 0, 'd3ad');
INSERT INTO personal_questions (soal, nomor, trait, reversed_score, quiz_code) VALUES ('Saya senang mendapatkan  perhatian dari para penguasa atau orang terkenal', 13, 'P', 0, 'd3ad');
INSERT INTO personal_questions (soal, nomor, trait, reversed_score, quiz_code) VALUES ('Saya meyakini rencana yang miliki menguntungkan bagi diri saya, bukan org lain', 14, 'M', 0, 'd3ad');
INSERT INTO personal_questions (soal, nomor, trait, reversed_score, quiz_code) VALUES ('Pembalasan yang diberikan harus perlu cepat dilaksanakan dengan bobot yang setimpal', 14, 'P', 0, 'd3ad');
INSERT INTO personal_questions (soal, nomor, trait, reversed_score, quiz_code) VALUES ('Kebanyakan orang bisa dimanipulasi untuk kepentingan saya', 15, 'M', 0, 'd3ad');
INSERT INTO personal_questions (soal, nomor, trait, reversed_score, quiz_code) VALUES ('Dalam Keadaan tertentu saya bisa berbuat jahat kepada orang lain', 15, 'P', 0, 'd3ad');
INSERT INTO personal_questions (soal, nomor, trait, reversed_score, quiz_code) VALUES ('Saya senang jika kebaikan saya dibandingkan dengan orang-orang terkenal', 16, 'N', 0, 'd3ad');
INSERT INTO personal_questions (soal, nomor, trait, reversed_score, quiz_code) VALUES ('Kebanyakan orang bisa dimanipulasi untuk kepentingan saya', 16, 'M', 0, 'd3ad');
INSERT INTO personal_questions (soal, nomor, trait, reversed_score, quiz_code) VALUES ('Saya tahu bahwa saya spesial karena setiap orang mengatakannya kepada saya', 17, 'N', 0, 'd3ad');
INSERT INTO personal_questions (soal, nomor, trait, reversed_score, quiz_code) VALUES ('Saya meyakini rencana yang miliki menguntungkan bagi diri saya, bukan org lain', 17, 'M', 0, 'd3ad');
INSERT INTO personal_questions (soal, nomor, trait, reversed_score, quiz_code) VALUES ('Saya senang jika saya dikenal oleh orang-orang penting', 18, 'N', 0, 'd3ad');
INSERT INTO personal_questions (soal, nomor, trait, reversed_score, quiz_code) VALUES ('Saya menggunakan cara dan taktik yang cerdas untuk mendapatkan apa yang saya inginkan', 18, 'M', 0, 'd3ad');
INSERT INTO personal_questions (soal, nomor, trait, reversed_score, quiz_code) VALUES ('Saya memaksa untuk mendapatkan rasa hormat yang seharusnya saya terima', 19, 'N', 0, 'd3ad');
INSERT INTO personal_questions (soal, nomor, trait, reversed_score, quiz_code) VALUES ('Saya harus menunggu waktu yang tepat untuk mendapatkan kembali para pengikut saya', 19, 'M', 0, 'd3ad');
INSERT INTO personal_questions (soal, nomor, trait, reversed_score, quiz_code) VALUES ('Banyak aktifitas kelompok yang nampaknya membosankan tanpa kehadiran saya', 20, 'N', 0, 'd3ad');
INSERT INTO personal_questions (soal, nomor, trait, reversed_score, quiz_code) VALUES ('Adalah wajar untuk menelusuri informasi yang dapat saya gunakan untuk berhadapan orang nantinya', 20, 'M', 0, 'd3ad');
INSERT INTO personal_questions (soal, nomor, trait, reversed_score, quiz_code) VALUES ('Dalam keadaan tertentu saya bisa berbuat jahat kepada orang lain', 21, 'P', 0, 'd3ad');
INSERT INTO personal_questions (soal, nomor, trait, reversed_score, quiz_code) VALUES ('Saya senang jika kebaikan saya dibandingkan dengan orang-orang terkenal', 21, 'N', 0, 'd3ad');
INSERT INTO personal_questions (soal, nomor, trait, reversed_score, quiz_code) VALUES ('Pembalasan yang diberikan harus perlu cepat dilaksanakan dengan bobot yang setimpal', 22, 'P', 0, 'd3ad');
INSERT INTO personal_questions (soal, nomor, trait, reversed_score, quiz_code) VALUES ('Saya tahu bahwa saya spesial karena setiap orang mengatakannya kepada saya', 22, 'N', 0, 'd3ad');
INSERT INTO personal_questions (soal, nomor, trait, reversed_score, quiz_code) VALUES ('Saya senang mendapatkan  perhatian dari para penguasa atau orang terkenal', 23, 'P', 0, 'd3ad');
INSERT INTO personal_questions (soal, nomor, trait, reversed_score, quiz_code) VALUES ('Saya senang jika saya dikenal oleh orang-orang penting', 23, 'N', 0, 'd3ad');
INSERT INTO personal_questions (soal, nomor, trait, reversed_score, quiz_code) VALUES ('Mereka yang pernah memiliki masalah dengan saya akan menyesal dikemudian hari', 24, 'P', 0, 'd3ad');
INSERT INTO personal_questions (soal, nomor, trait, reversed_score, quiz_code) VALUES ('Saya memaksa untuk mendapatkan rasa hormat yang seharusnya saya terima', 24, 'N', 0, 'd3ad');
INSERT INTO personal_questions (soal, nomor, trait, reversed_score, quiz_code) VALUES ('Saya akan mengatakan apapun untuk mendapatkan apa yang saya inginkan', 25, 'P', 0, 'd3ad');
INSERT INTO personal_questions (soal, nomor, trait, reversed_score, quiz_code) VALUES ('Banyak aktifitas kelompok yang nampaknya membosankan tanpa kehadiran saya', 25, 'N', 0, 'd3ad');
INSERT INTO personal_questions (soal, nomor, trait, reversed_score, quiz_code) VALUES ('Dalam Keadaan tertentu saya bisa berbuat jahat kepada orang lain', 26, 'P', 0, 'd3ad');
INSERT INTO personal_questions (soal, nomor, trait, reversed_score, quiz_code) VALUES ('Kebanyakan orang bisa dimanipulasi untuk kepentingan saya', 26, 'M', 0, 'd3ad');
INSERT INTO personal_questions (soal, nomor, trait, reversed_score, quiz_code) VALUES ('Pembalasan yang diberikan harus perlu cepat dilaksanakan dengan bobot yang setimpal', 27, 'P', 0, 'd3ad');
INSERT INTO personal_questions (soal, nomor, trait, reversed_score, quiz_code) VALUES ('Saya meyakini rencana yang dimiliki menguntungkan bagi diri saya, bukan orang lain', 27, 'M', 0, 'd3ad');
INSERT INTO personal_questions (soal, nomor, trait, reversed_score, quiz_code) VALUES ('Saya senang mendapatkan  perhatian dari para penguasa atau orang terkenal', 28, 'P', 0, 'd3ad');
INSERT INTO personal_questions (soal, nomor, trait, reversed_score, quiz_code) VALUES ('Saya menggunakan cara dan taktik yang cerdas untuk mendapatkan apa yang saya inginkan', 28, 'M', 0, 'd3ad');
INSERT INTO personal_questions (soal, nomor, trait, reversed_score, quiz_code) VALUES ('Mereka yang pernah memiliki masalah dengan saya akan menyesal dikemudian hari', 29, 'P', 0, 'd3ad');
INSERT INTO personal_questions (soal, nomor, trait, reversed_score, quiz_code) VALUES ('Saya harus menunggu waktu yang tepat untuk mendapatkan kembali para pengikut saya', 29, 'M', 0, 'd3ad');
INSERT INTO personal_questions (soal, nomor, trait, reversed_score, quiz_code) VALUES ('Saya akan mengatakan apapun untuk mendapatkan apa yang saya inginkan', 30, 'P', 0, 'd3ad');
INSERT INTO personal_questions (soal, nomor, trait, reversed_score, quiz_code) VALUES ('Adalah wajar untuk menelusuri informasi yang dapat saya gunakan untuk berhadapan orang nantinya', 30, 'M', 0, 'd3ad');
