INSERT INTO personal_questions (soal, nomor, trait, reversed_score, quiz_code) VALUES ('Saya selalu meminta ijin jika akan menggunakan masukan orang lain untuk menyelesaikan masalah yang saya hadapi', 1, 'Sin', 0, 'hexaco');
INSERT INTO personal_questions (soal, nomor, trait, reversed_score, quiz_code) VALUES ('Saya merasa tidak perlu meminta maaf ketika saya melakukan kesalahan', 2, 'Sin', 1, 'hexaco');
INSERT INTO personal_questions (soal, nomor, trait, reversed_score, quiz_code) VALUES ('Saya selalu mengikuti masukan dari rekan kerja saya karena tidak ingin membuat ia kecewa', 3, 'Sin', 0, 'hexaco');
INSERT INTO personal_questions (soal, nomor, trait, reversed_score, quiz_code) VALUES ('Saya menerima barang atau uang dari supplier/kontraktor karena merasa sungkan dengan teman-teman yang sudah menerima duluan', 4, 'Fair', 1, 'hexaco');
INSERT INTO personal_questions (soal, nomor, trait, reversed_score, quiz_code) VALUES ('Saya tetap akan mendukung atasan saya yang melakukan pelanggaran aturan dalam bekerja', 5, 'Fair', 1, 'hexaco');
INSERT INTO personal_questions (soal, nomor, trait, reversed_score, quiz_code) VALUES ('Saya akan mengikuti permintaan rekan kerja untuk menerima imbalan dari pihak ketiga daripada ditinggalkan oleh mereka', 6, 'Fair', 1, 'hexaco');
INSERT INTO personal_questions (soal, nomor, trait, reversed_score, quiz_code) VALUES ('Saya hanya memakai alat komunikasi yang paling canggih untuk  mendukung saya dalam bekerja', 7, 'GreedA', 1, 'hexaco');
INSERT INTO personal_questions (soal, nomor, trait, reversed_score, quiz_code) VALUES ('Saya  selalu  membawa laptop terbaru saya di setiap meeting dengan  mitra kerja', 8, 'GreedA', 1, 'hexaco');
INSERT INTO personal_questions (soal, nomor, trait, reversed_score, quiz_code) VALUES ('Saya selalu menggunakan mobil kantor untuk  semua aktivitas saya baik untuk urusan kantor maupun di luar kantor', 9, 'GreedA', 1, 'hexaco');
INSERT INTO personal_questions (soal, nomor, trait, reversed_score, quiz_code) VALUES ('Sebagai pegawai, saya telah memahami semua fasilitas yang seharusnya saya terima sesuai dengan jabatan saya.', 10, 'Modes', 0, 'hexaco');
INSERT INTO personal_questions (soal, nomor, trait, reversed_score, quiz_code) VALUES ('Selama ini saya mendapatkan fasilitas kerja sesuai dengan jabatan saya', 11, 'Modes', 0, 'hexaco');
INSERT INTO personal_questions (soal, nomor, trait, reversed_score, quiz_code) VALUES ('Ketika merasa tidak enak badan saya langsung mengambil jatah cuti karena saya takut penyakitnya semakin parah.', 12, 'Fear', 1, 'hexaco');
INSERT INTO personal_questions (soal, nomor, trait, reversed_score, quiz_code) VALUES ('Setiap sakit  saya harus memeriksakan ke berbagai dokter spesialis untuk mendapatkan kepastian mengenai penyakit saya.', 13, 'Fear', 1, 'hexaco');
INSERT INTO personal_questions (soal, nomor, trait, reversed_score, quiz_code) VALUES ('Saya segera memeriksakan diri ke dokter apabila merasa pusing.', 14, 'Fear', 1, 'hexaco');
INSERT INTO personal_questions (soal, nomor, trait, reversed_score, quiz_code) VALUES ('Saya cemas menghadapi masa depan saya.', 15, 'Anx', 1, 'hexaco');
INSERT INTO personal_questions (soal, nomor, trait, reversed_score, quiz_code) VALUES ('Perut saya mendadak sakit ketika dipanggil oleh atasan saya.', 16, 'Anx', 1, 'hexaco');
INSERT INTO personal_questions (soal, nomor, trait, reversed_score, quiz_code) VALUES ('Tuntutan pekerjaan yang baru membuat saya tertekan.', 17, 'Anx', 1, 'hexaco');
INSERT INTO personal_questions (soal, nomor, trait, reversed_score, quiz_code) VALUES ('Saya lebih nyaman apabila orang lain yang membuat keputusan', 18, 'Depen', 0, 'hexaco');
INSERT INTO personal_questions (soal, nomor, trait, reversed_score, quiz_code) VALUES ('Setiap kali akan menentukan pilihan saya harus yakin mendapatkan persetujuan dari orang lain', 19, 'Depen', 0, 'hexaco');
INSERT INTO personal_questions (soal, nomor, trait, reversed_score, quiz_code) VALUES ('Saya merasa cemas  jika harus mengambil inisiatif untuk memulai suatu perubahan', 20, 'Depen', 1, 'hexaco');
INSERT INTO personal_questions (soal, nomor, trait, reversed_score, quiz_code) VALUES ('Saya merasa prihatin dengan penderitaan yang dialami oleh oranglain', 21, 'Senti', 1, 'hexaco');
INSERT INTO personal_questions (soal, nomor, trait, reversed_score, quiz_code) VALUES ('Saya sulit melupakan orang yang berjasa dalam kehidupan saya', 22, 'Senti', 1, 'hexaco');
INSERT INTO personal_questions (soal, nomor, trait, reversed_score, quiz_code) VALUES ('Saya sulit melupakan peristiwa-peristiwa penting yang mengubah kehidupan saya', 23, 'Senti', 1, 'hexaco');
INSERT INTO personal_questions (soal, nomor, trait, reversed_score, quiz_code) VALUES ('Saya merasa bahwa orang lain menghargai saya.', 24, 'SocSelfES', 0, 'hexaco');
INSERT INTO personal_questions (soal, nomor, trait, reversed_score, quiz_code) VALUES ('Teman-teman saya memiliki penilaian yang positif mengenai diri saya.', 25, 'SocSelfES', 0, 'hexaco');
INSERT INTO personal_questions (soal, nomor, trait, reversed_score, quiz_code) VALUES ('Saya merasa kesulitan untuk dapat membuat lingkungan menyukai saya.', 26, 'SocSelfES', 1, 'hexaco');
INSERT INTO personal_questions (soal, nomor, trait, reversed_score, quiz_code) VALUES ('Saat rapat saya lebih senang meminta rekan kerja yang lain untuk menyampaikan pendapat saya daripada harus menyampaikan sendiri pendapat saya.', 27, 'Sbold', 0, 'hexaco');
INSERT INTO personal_questions (soal, nomor, trait, reversed_score, quiz_code) VALUES ('Saya berani membuka topik pembicaraan saat bertemu dengan orang baru.', 28, 'Sbold', 0, 'hexaco');
INSERT INTO personal_questions (soal, nomor, trait, reversed_score, quiz_code) VALUES ('Dalam tiap kegiatan kantor, saya berani untuk terlebih dahulu mengajak berkenalan orang-orang yang belum saya kenal.', 29, 'Sbold', 0, 'hexaco');
INSERT INTO personal_questions (soal, nomor, trait, reversed_score, quiz_code) VALUES ('Saya senang melakukan aktivitas sendirian saja.', 30, 'Soc', 1, 'hexaco');
INSERT INTO personal_questions (soal, nomor, trait, reversed_score, quiz_code) VALUES ('Saya menikmati kegiatan mengobrol dengan teman-teman di kantor saya.', 31, 'Soc', 0, 'hexaco');
INSERT INTO personal_questions (soal, nomor, trait, reversed_score, quiz_code) VALUES ('Saya merupakan orang yang ceria.', 32, 'Live', 0, 'hexaco');
INSERT INTO personal_questions (soal, nomor, trait, reversed_score, quiz_code) VALUES ('Kehadiran saya dapat menghidupkan suasana dalam kelompok.', 33, 'Live', 0, 'hexaco');
INSERT INTO personal_questions (soal, nomor, trait, reversed_score, quiz_code) VALUES ('Keceriaan merupakan hal yang penting untuk ditunjukkan dalam kelompok.', 34, 'Live', 0, 'hexaco');
INSERT INTO personal_questions (soal, nomor, trait, reversed_score, quiz_code) VALUES ('Saya mudah memaafkan orang lain', 35, 'Forg', 0, 'hexaco');
INSERT INTO personal_questions (soal, nomor, trait, reversed_score, quiz_code) VALUES ('Saya tetap berinteraksi dengan orang yang pernah menyakiti hati saya', 36, 'Forg', 0, 'hexaco');
INSERT INTO personal_questions (soal, nomor, trait, reversed_score, quiz_code) VALUES ('Saya tetap membantu orang yang pernah bersilisih paham dengan saya', 37, 'Forg', 0, 'hexaco');
INSERT INTO personal_questions (soal, nomor, trait, reversed_score, quiz_code) VALUES ('Saya menerima dengan mudah permintaan maaf dari orang lain', 38, 'Forg', 0, 'hexaco');
INSERT INTO personal_questions (soal, nomor, trait, reversed_score, quiz_code) VALUES ('Saya senang membantu orang lain', 39, 'Gent', 0, 'hexaco');
INSERT INTO personal_questions (soal, nomor, trait, reversed_score, quiz_code) VALUES ('Saya senang menolong tanpa pamrih', 40, 'Gent', 0, 'hexaco');
INSERT INTO personal_questions (soal, nomor, trait, reversed_score, quiz_code) VALUES ('Saya senang berinteraksi dengan orang banyak', 41, 'Gent', 0, 'hexaco');
INSERT INTO personal_questions (soal, nomor, trait, reversed_score, quiz_code) VALUES ('Saya mau menang sendiri jika sedang berdiskusi', 42, 'Flex', 0, 'hexaco');
INSERT INTO personal_questions (soal, nomor, trait, reversed_score, quiz_code) VALUES ('Saya suka memberikan saran demi kemajuan bersama', 43, 'Flex', 0, 'hexaco');
INSERT INTO personal_questions (soal, nomor, trait, reversed_score, quiz_code) VALUES ('Saya selalu ingin damai dan rukun dengan siapa saja', 44, 'Flex', 0, 'hexaco');
INSERT INTO personal_questions (soal, nomor, trait, reversed_score, quiz_code) VALUES ('Saya dapat menerima kritik dengan pikiran yang jernih', 45, 'Pat', 0, 'hexaco');
INSERT INTO personal_questions (soal, nomor, trait, reversed_score, quiz_code) VALUES ('Saya berusaha sabar menghadapi orang yang membuat saya marah', 46, 'Pat', 0, 'hexaco');
INSERT INTO personal_questions (soal, nomor, trait, reversed_score, quiz_code) VALUES ('Saya orang yang pendiam.', 47, 'Pat', 0, 'hexaco');
INSERT INTO personal_questions (soal, nomor, trait, reversed_score, quiz_code) VALUES ('Barang-barang di ruang kerja saya tersimpan dengan tertib pada tempatnya', 48, 'Org', 0, 'hexaco');
INSERT INTO personal_questions (soal, nomor, trait, reversed_score, quiz_code) VALUES ('Ruang kerja yang tidak teratur menyulitkan saya untuk bekerja dengan baik', 49, 'Org', 0, 'hexaco');
INSERT INTO personal_questions (soal, nomor, trait, reversed_score, quiz_code) VALUES ('Saya selalu ingat dimana berkas pekerjaan saya diletakkan', 50, 'Org', 0, 'hexaco');
INSERT INTO personal_questions (soal, nomor, trait, reversed_score, quiz_code) VALUES ('Bekerja lembur menyita waktu pribadi saya yang amat berharga', 51, 'Dilg', 0, 'hexaco');
INSERT INTO personal_questions (soal, nomor, trait, reversed_score, quiz_code) VALUES ('Menyerahkan laporan melewati batas waktu yang ditetapkan adalah hal yang wajar', 52, 'Dilg', 1, 'hexaco');
INSERT INTO personal_questions (soal, nomor, trait, reversed_score, quiz_code) VALUES ('Saya merasa terpaksa bila mengerjakan tugas yang berada di luar pengalaman saya', 53, 'Dilg', 1, 'hexaco');
INSERT INTO personal_questions (soal, nomor, trait, reversed_score, quiz_code) VALUES ('Saya merasa malu bila tidak dapat menyelesaikan tugas yang diberikan kepada saya', 54, 'Perfect', 1, 'hexaco');
INSERT INTO personal_questions (soal, nomor, trait, reversed_score, quiz_code) VALUES ('Saya tidak mudah puas dengan prestasi kerja yang sudah saya capai', 55, 'Perfect', 0, 'hexaco');
INSERT INTO personal_questions (soal, nomor, trait, reversed_score, quiz_code) VALUES ('Saya terus menerus memperbaiki hasil kerja saya sampai batas waktu yang ditentukan', 56, 'Perfect', 0, 'hexaco');
INSERT INTO personal_questions (soal, nomor, trait, reversed_score, quiz_code) VALUES ('Saya menyiapkan fakta dan informasi terlebih dahulu sebelum menegur rekan kerja yang bekerja seenaknya', 57, 'Pruden', 0, 'hexaco');
INSERT INTO personal_questions (soal, nomor, trait, reversed_score, quiz_code) VALUES ('Pendapat orang lain sangat berharga dalam membantu saya mengambil keputusan', 58, 'Pruden', 0, 'hexaco');
INSERT INTO personal_questions (soal, nomor, trait, reversed_score, quiz_code) VALUES ('Saya mencari sumber informasi yang otentik ketika menerima adanya informasi baru dari rekan kerja', 59, 'Pruden', 0, 'hexaco');
INSERT INTO personal_questions (soal, nomor, trait, reversed_score, quiz_code) VALUES ('Saya mengagumi karya seni lukisan yang dibuat oleh para maestro seniman', 60, 'AA', 0, 'hexaco');
INSERT INTO personal_questions (soal, nomor, trait, reversed_score, quiz_code) VALUES ('Pada waktu senggang saya manfaatkan untuk mengunjungi pagelaran kesenian drama kolosal', 61, 'AA', 0, 'hexaco');
INSERT INTO personal_questions (soal, nomor, trait, reversed_score, quiz_code) VALUES ('Saya memasang lukisan bermotif bali untuk memperindah ruang kerja saya', 62, 'AA', 0, 'hexaco');
INSERT INTO personal_questions (soal, nomor, trait, reversed_score, quiz_code) VALUES ('Saya akan mencari tau pengalaman yang dialami oleh orang lain terkait dengan caranya menyesuaikan diri dengan budaya yang baru', 63, 'Inq', 0, 'hexaco');
INSERT INTO personal_questions (soal, nomor, trait, reversed_score, quiz_code) VALUES ('Saya antusias mempelajari sejarah dan perkembangan budaya di suatu daerah', 64, 'Inq', 0, 'hexaco');
INSERT INTO personal_questions (soal, nomor, trait, reversed_score, quiz_code) VALUES ('Saya mencari informasi dari berbagai sumber yang dapat menjelaskan mengenai kejadian tsunami', 65, 'Inq', 0, 'hexaco');
INSERT INTO personal_questions (soal, nomor, trait, reversed_score, quiz_code) VALUES ('Saya merasa tertantang untuk mencari cara yang  belum pernah dicoba oleh orang lain dalam menyelesaikan masalah', 66, 'Crea', 0, 'hexaco');
INSERT INTO personal_questions (soal, nomor, trait, reversed_score, quiz_code) VALUES ('Saya senang jika ada orang lain yang meragukan, mempertanyakan  dan ingin menguji ide baru yang saya sampaikan sehingga saya lebih tertantang untuk mengembangkan ide-ide yang lebih inovatif', 67, 'Crea', 0, 'hexaco');
INSERT INTO personal_questions (soal, nomor, trait, reversed_score, quiz_code) VALUES ('Saya bisa menanggung resiko jika ternyata ide yang saya terapkan tidak bisa menyelesaikan masalah', 68, 'Crea', 0, 'hexaco');
INSERT INTO personal_questions (soal, nomor, trait, reversed_score, quiz_code) VALUES ('Saya lebih bersemangat menerapkan cara baru untuk menyelesaikan masalah', 69, 'Uncon', 0, 'hexaco');
INSERT INTO personal_questions (soal, nomor, trait, reversed_score, quiz_code) VALUES ('Saya bisa menerima sudut pandang yang berbeda-beda dalam  menyelesaikan masalah ataupun mencapai target kerja', 70, 'Uncon', 0, 'hexaco');
INSERT INTO personal_questions (soal, nomor, trait, reversed_score, quiz_code) VALUES ('Saya membutuhkan waktu yang cukup lama untuk membaca suatu kontrak kerja secara berulang ulang sebelum menandatanganinya', 71, 'Uncon', 0, 'hexaco');
INSERT INTO personal_questions (soal, nomor, trait, reversed_score, quiz_code) VALUES ('Saya menikmati saat-saat kebersamaan bersama teman', 72, 'Soc', 0, 'hexaco');
